### ISSUE TITLE
Restructure Clauses 7, 8, and 9

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#100]
The candidate standard does not clearly present the EDR Queries. They are obscured by too much generic OGC stuff.

The central clauses/chapters need restructuring.

**Comment by chris-little** [comment]
Not perfect, but getting there. Can we make an  HTML doc of the PR to look at before the SWG? I pressed a few buttons, but nothing seemed to happen on my machines.

**Comment by dblodgett-usgs** [comment]
[EDR-candidate-specification.html.zip](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/files/4962718/EDR-candidate-specification.html.zip)

Download and open locally.
