### ISSUE TITLE
How to reference EDRFeatureCollectionGeoJSON schema?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#108]
We have this: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/openapi/EDR_OpenAPI.yaml#L2200

But it's not in: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/tree/master/candidate-standard/openapi/schemas to link to. 

What's our strategy for linking to json schemas in general? Noting that the link to collections.json is broken in table 11 currently.

**Comment by m-burgoyne** [comment]
I think it would be worth refactoring the OpenAPI schema to break out the individual data response schemas into seperate files. Store those response and data schemas in [/candidate-standard/openapi/schemas](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/tree/master/candidate-standard/openapi/schemas)  and reference them from the parent [OpenAPI definition]( https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/openapi/EDR_OpenAPI.yaml).

**Comment by chris-little** [comment]
agreed to call it something like QueryEndpoint?

**Comment by dblodgett-usgs** [comment]
Will rename "uri" in the EDRFeatureCollectionGeoJSON to "edrQueryEndpoint"

**Comment by chris-little** [comment]
Agreed to close at SWG 23
