### ISSUE TITLE
Abstract Tests for collections are confusing...

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#110]
In the work I'm doing on #98, I am getting really confused by what's in https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/abstract_tests/ATS_class_collections.adoc

It's because the collections are referred to as "items" -- which they are, in a list of collections. 

The first thing I did is remove the features (items) ATS here: https://github.com/dblodgett-usgs/Environmental-Data-Retrieval-API/commit/564d66984f853ba26f1faf67148fb8dcc6aa06ae 

I'm also renaming ATS_rc-md-items.adoc, ATS_rc-md-items-links.adoc, and ATS_rc-md-items-table.adoc to  
ATS_rc-md-collection-info.adoc, ATS_rc-md-collection-info-links.adoc, and ATS_rc-md-collection-info-table.adoc

Just opening this issue for the record and to spur conversation if it needs to happen.

**Comment by chris-little** [comment]
Agreed words clarified by not overloading 'items'
But @ghobona will check meaning of URI terms

**Comment by ghobona** [comment]
I have received clarification from @cportele.

The use of "md" there is legacy. It is short for "metadata" and reflects an early version of the names/terminology of the resources. 

There's no need for the EDR API to use "md" in its URIs.

**Comment by dblodgett-usgs** [comment]
OK, I'll factor the -md- out in my refactor of the requirements.

**Comment by dblodgett-usgs** [comment]
Actually, looking at this, I think a lot of these references should actually go to features or maybe common? 

e.g. `Requirement | /req/collections/rc-md-collection-info-links` 

EDR doesn't have a collection-info-links requirement. Unless I'm really not following what these should link to...

**Comment by dblodgett-usgs** [comment]
Will have these links go to API common rather than creating new requirements in our spec. Need to create the links once they exist for API-Common.

**Comment by dblodgett-usgs** [comment]
See common spec for final URIs to link to.

**Comment by chris-little** [comment]
@dblodgett-usgs the PR from @m-burgoyne sorted Common references into Common Core and Collections.
Any other changes left to do, otherwise we can close the issue

**Comment by chris-little** [comment]
Agreed to close 2020-10-15
