### ISSUE TITLE
cross-reference.adoc missing some items...

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#111]
requirements/core/REQ_rc-md-items.adoc and requirements/core/REQ_rc-md-items-links.adoc are missing in the repo but linked in cross-reference.adoc -- not clear to me what that file is actually for, but figured I'd note it.

**Comment by chris-little** [comment]
Gobe says we can remove it. Not required for AsciiDoc template
