### ISSUE TITLE
Support for 'items' query in the EDR API and OGC API - Features

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/Environmental-Data-Retrieval-API#116]
The EDR API is compatible with OGC API-Features as it [supports](http://docs.opengeospatial.org/DRAFTS/19-086.html#rc_items-section) `items`. However, generally the items "do not exist in advance of query". 

So within the EDR API `/collections/{collectionId}/items` is defined as a type of query.

Is the behaviour of `/collections/{collectionId}/items` in EDR the same as in OGC API - Features?

If not, does the EDR API adequately clarify the difference in semantics and/or behaviour.

Please coordinate with the OGC API - Features SWG on this discussion.

**Comment by m-burgoyne** [comment]
The intention is the behaviour of `/collections/{collectionId}/items` in EDR will be the same as in OGC API - Features - Part 1: Core

**Comment by dblodgett-usgs** [comment]
@ghobona -- the intent is that the items endpoint of an EDR collection will have pre-existing items. 

See:
http://docs.opengeospatial.org/DRAFTS/19-086.html#rc_items-section

**Comment by ghobona** [comment]
@cportele and @pvretano

Any thoughts on this?

**Comment by cportele** [comment]
@ghobona - The behaviour of the resource as described in the text looks good to me. There are no normative statements, so this section is only an informative discussion anyhow - not sure, if this intentional. 

What may be a general point of discussion are terminology differences/changes. The name of the resource in OGC API Features is "Features", but EDR renames it to "EDR Items query", which is confusing to me and might be seen as an indication that it is a different resource type.

---
By the way, it is not clear to me where the quote in the opening comment that items "do not exist in advance of query" comes from. It clearly does not apply to the sampling features that can be retrieved at the Features resource. A search in the document does not have a match either.

**Comment by ghobona** [comment]
@cportele  Thanks for the feedback.

The comment that "items do not exist in advance of query" was copied from the Cross-SWG matrix that was recently completed by the Cross-SWG reps.

**Comment by cportele** [comment]
@ghobona - Thanks, so I guess that statement is OBE.

**Comment by chris-little** [comment]
@cportele @ghobona I suspect that I originally wrote the words to the effect `items do not exist in advance of query` to clarify answers to the question of what are the resources in an EDR API. I think we ended up with a better description along the lines of: `generally queries are transient resources`. 
As we started out by tracking  OGC API - Features closely, we were reluctant to ditch 'items'. We then realised persisting queries, as a resource, would be useful. I would be reluctant to adopt a 'pure' Features terminology, as this is not a traditional interpretation of a feature, though a feature it undoubtedly is.
We also use Items as a traditional features, for example, to retrieve data for a named location as a user convenience when they maya not know the required coordinates.

Mark Burgoyne has recently demo'ed a client performing an asynchronous (longish duration) query, with the query and potential results stored (somewhere) for access, or even re-use. Is this storage and reuse of queries something to address in Common or Records?

**Comment by pvretano** [comment]
@chris-little not yet but elements of stored queries, asynchronous execution and pub/sub enabled feature servers have been exercised in testbeds over the last few years,

A light-weight asynchronous query capability based on OGC API - Features was tested and documented in TB14.  See here: https://docs.opengeospatial.org/per/18-045.html#async_extension

As for stored queries ... Stored queries were part of the WFS 2.0 specification.  Back in the day when we were groping around for what a REST API for WFS might look like I wrote this: https://portal.ogc.org/files/?artifact_id=44852&version=1 which included a section on stored queries.

I have been planning to update the stored query ideas in that document and apply then to the current OGC API design pattern.  My current thinking goes something like this ...

To create a new stored query, some query expression is POSTed to the **/collection/{collectionId}/queries** endpoint.  The query expression can be encoded in any language that the client and server negotiate (e.g. CQL, GraphQL, etc.).  In the following example I show a skeleton GraphQL query but that is just to illustrate the point.

```
CLIENT                                                     SERVER
  |                                                          |
  | POST /collections/{collectionId}/queries   HTTP/1.1      |
  | Content-Type: application/json                           |
  |                                                          |
  | {                                                        |
  |    "query": "...",                                       |
  |    "operationName": "...",                               |
  |    "variables": { "myVariable": "someValue", ... }       |
  | }                                                        |
  |--------------------------------------------------------->|
  |                                                          |
  | HTTP/1.1 201 Created                                     |
  | Location: /collections/{collectionId}/queries/q1013      |
  |<---------------------------------------------------------|
```
The server responds with a 201 to let the client know that the stored query was created and the Location header gives the URL of the resource; in this case **/collections/{collectionId}/queries/q1013**.

The client can subsequently execute the stored query by simply doing a GET on the query resource. 

```
CLIENT                                                     SERVER
  |                                                          |
  | GET /collections/{collectionId}/queries/q1013&limit=100   HTTP/1.1 |
  | Accept: application/geo+json                             |
  |--------------------------------------------------------->|
  |                                                          |
  | HTTP/1.1 200 OK                                          |
  | Content-Type: application/json                           |
  |                                                          |
  | {                                                        |
  |    ... GeoJSON feature collection ...                    |
  | }                                                        |
  |<---------------------------------------------------------|
```
In this example the client has requested GeoJSON output and has set the paging limit to 100.  The server responds exactly as it would for an ad-hoc query (i.e. a feature collection containing the results of the query at the time the query was run).

To execute a query asynchronously, the client can simply append a responseHandler parameter to the query:

`GET /collections/{collectionId}/queries/q1013?responseHandler=mailto:pvretano@cubewerx.com`

and the server will run the query in the background, taking as long as necessary, and then sending a notification to the specified handler when execution is complete and the result is availables.   Here I show an email notification but other schemes are possible too, SMS, URL callback, etc...  All this is detailed in the async reference I provided at the top of the post.

Periodic or event triggered execution (e.g. whenever new data is added for example) of the query could also be arranged by overlaying a PubSub API (much longer email).  I actually demonstrated this a few testbeds ago (see this video: https://eratosthenes.pvretano.com/Projects/tb12/WFS_PubSub/LSA_A037_PubSub_WFS_Demontration.mp4).  Gees, I sound like a robot! :)

The PUT or PATCH operations could be used to modify an existing query.

Doing a GET on the /collections/{collectionId}/queries endpoint would return the list of stored queries.

```
CLIENT                                                     SERVER
  |                                                          |
  | GET /collections/{collectionId}/queries   HTTP/1.1       |
  | Accept: application/json                                 |
  |--------------------------------------------------------->|
  |                                                          |
  | HTTP/1.1 200 OK                                          |
  | Content-Type: application/json                           |
  |                                                          |
  | {                                                        |
  |    "queries": [                                          |
  |       {                                                  |
  |          "id": "q1013",   .                              |
  |          "query": { ... }                                |
  |       },                                                 |
  |       .                                                  |
  |       .                                                  |
  |       .                                                  |
  |    ]                                                     |
  | }                                                        |
  |<---------------------------------------------------------|
```
If your query needs to run across multiple collections (e.g. join) then there could also be a top-level /queries endpoint that behaves the same way but allows cross-collection queries to be created.

There are quite a few details that I have not included in this post.  However, I have it on my todo list of sketch out an extension for stored queries when I have some time.

Does this sound like something that EDR is looking for?

B.T.W.  This is not pie-in-the-sky speculation.  WFS 2.0 had support for stored queries so our server supported that.  I also added a REST API to our WFS 2.0 implementation of stored queries as described in the document I referenced at the top of this POST.  At some point I will update that implementation to behave as I have described here.

Sorry for the length ... you hit an interest of mine ... hope this is useful.

**Comment by dblodgett-usgs** [comment]
Thanks for the references and thorough description, @pvretano. What @m-burgoyne specified is a spin on the asynchronous polling scheme described in your TB14 ER but using a 308 redirect to the location that the result will be available when it's done. See: http://docs.opengeospatial.org/DRAFTS/19-086.html#asynchronous_queries

I really like the responseHandler idea as a way to control the asynchronous behavior. EDR is going to need an asynchronous scheme one way or the other but we want to keep it as simple as possible.

**Comment by m-burgoyne** [comment]
The suggested approach for EDR is more basic than the one described by : http://docs.opengeospatial.org/DRAFTS/19-086.html#asynchronous_queries, it sacrifices a some of the functionality but this is with a view to making it as easy as possible for a wide variety of technologies and data sources to support an asynchronous capability.  

The richer the functionality (i.e. the ability for the client to cancel requests) the more technically complex and capable the server implementation has to be,  the implementation as described in the EDR docs is just intended as a mechanism to respond to API queries which require longer time periods to complete (returning an error message stating that the request would take too long to execute will also be a valid response). 

A weakness of the proposed approach is that it does not check if the user still wants to execute the request if the response will require a long period of time to complete,  a strength is that it is built around the proposed EDR API’s so wouldn’t require major changes to the behavior of a client application.

**Comment by chris-little** [comment]
@dblodgett-usgs @m-burgoyne Let's discuss this this afternoon. If it is easy to add functionality to Mark's client, let's stick with what we've got, and the next version could fit with the full Pub/Sub/Asynchronous/Paged/StoredQuery efforts.
I think that when the client receives a 'data available in n seconds' message is the time to allow the user to rescind their query.

**Comment by dblodgett-usgs** [comment]
This issue needs to be split into one about asynchronous and one about items. Items is settled for the most part and asynchronous needs to be planned more thoroughly.

**Comment by ghobona** [comment]
Closing this issue because the 'items' topic is settled (see https://github.com/opengeospatial/Environmental-Data-Retrieval-API/issues/116#issuecomment-677662916).
