### ISSUE TITLE
Consistency in describing JSON, GeoJSON, CoverageJSON and HTML support 

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/Environmental-Data-Retrieval-API#119]
The following sections imply that JSON, GeoJSON, CoverageJSON and HTML are requirements. However, Section 10.7 suggests that support for these encodings is a Recommendation.

* A.4. Conformance Class JSON
* A.4.1. JSON Definition
* A.5. Conformance Class GeoJSON
* A.5.1. JSON Definition
* A.5.2. GeoJSON Content
* A.6. Conformance Class EDR GeoJSON
* A.6.1. EDR GeoJSON Definition
* A.6.2. EDR GeoJSON Content
* A.7. Conformance Class CoverageJSON
* A.7.1. CoverageJSON Definition
* A.7.2. CoverageJSON Content
* A.8. Conformance Class HTML
* A.8.1. HTML Definition
* A.8.2. HTML Content

The sections in the Annex need to be updated to be consistent with Section 10.7

**Comment by ghobona** [comment]
Please note this comment from @cnreediii in relation to a different OGC API standard https://github.com/opengeospatial/OGC-API-Tiles/issues/29

I think the comment is applicable to CoverageJSON.

**Comment by ghobona** [comment]
To clarify, in section 10.7 the encodings are listed as Recommendations.

![Screenshot 2020-08-06 at 07 43 40](https://user-images.githubusercontent.com/18121038/89499928-bb9ffc80-d7b8-11ea-95a4-065e416b07e1.png)

However in the Annex, the URIs identify them as Requirements.

![Screenshot 2020-08-06 at 07 43 13](https://user-images.githubusercontent.com/18121038/89499967-cce90900-d7b8-11ea-9639-717d1f03e4fc.png)

**Comment by dblodgett-usgs** [comment]
@ghobona -- We've been discussing how to handle this. The plan is to change the annotations to recommendations and link to the recommendations. I'll close this issue when that change has been applied.

**Comment by ghobona** [comment]
@dblodgett-usgs Sounds good. I'm happy with that approach.

**Comment by dblodgett-usgs** [comment]
This will be handled in #112
