### ISSUE TITLE
EDR and OGC-API Features

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#12]
To enhance compatibility with OGC-API Features, I want to advocate for two modifications.

1) Make collection instance (version) in the API path optional.
2) Allow an "items" endpoint for an EDR collection.

I think this can be achieved flexibly without any great change to how we envision things functioning. 

If we consider that,  
1) a collection instance could itself be a collection (as they can in OGC-API Features), and  
2) that an _EDR_ collection could be a collection of items _**or**_ a collection of EDR collection instances. 

It would follow that each of those EDR collection instances could then be a collection of items. 

This would allow a path like:

`/collections/items`

To provide a list of previously run feature queries with query geometries if desired _or_ a list of item (site) IDs with site locations.

or a path like:

`collections/latest/items` 

to do the same.

I see no reason to get fancy with what the json-schema is here. An EDR collection's item view would use the same json-keys as the API query parameters `id`, `parametername`, etc. and/or could adopt from the collection instance information schema.

I think this would allow a simple site-based / observational EDR service where the idea of a collection instance doesn't make sense to fit much more naturally while still allowing the fully-fledged collection version/instance use case that is desired. It also solves the issue of how to advertise what items are available.

Maybe a little half baked, but based on my read of the draft spec, this might help with scope and fix the issue of advertising what items are available.

**Comment by tervo** [comment]
I find these suggestions as very good ideas. Compatibility with OGC-API Features would greatly increase usability of the standard and make the service easier for users. OGC-API Features is already widely considered in many cases and compatibility in simple use cases is crucial for a success of this API. 

Version info is an important aspect for some special cases but in many use cases there are no different versions available or people are only interest in the latest version. In these cases, version info only make API more cumbersome. 

A similar scene applies for geometry endpoint also. In many cases, publisher may want to provide only one type of feature in one service (endpoint). In these cases, the geometry in the path provide a very little value but it do make end users life more complicated since "standard" clients (for OGC-API Features) can't handle the request.

**Comment by dr-shorthair** [comment]
What is 'geometry endpoint'?

**Comment by tervo** [comment]
Sorry for being vague. With 'geometry endpoint' I mean path ending with a desired geometry (`.../point`)

**Comment by dr-shorthair** [comment]
Do you have an example of a path ending with a desired geometry (.../point) or where it is described in an adopted or drafted specification? (Can't find it in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0 for example)

**Comment by tervo** [comment]
I mean quite opposite. It is an idea in EDR but it's NOT part of OGC-API Features which why I would like that to be optional also in EDR.

**Comment by dblodgett-usgs** [comment]
@tervo you are referring to the idea that in the current draft, table 3 has various query types that are accessed through an endpoint like:
`/collections/{collection}/{instance}/{query_type}` right?

I see the `query_type` indicator as a way to access functionality that would only be available in EDR -- so we wouldn't really want that to be compatible with API Features, right? 

`/collections/{collection}/{instance}/items` would list pre-existing "EDR queries" that might be compatible with features. "EDR queries" is meant to be things like pre-existing geometries for querying the collection or things like monitoring stations.

Is there another approach that you have in mind?

**Comment by tervo** [comment]
Exactly, thank you for the clarification!

**Comment by m-burgoyne** [comment]
I am definitely in favour of keeping the API compatible with the OGC-Features API, so this suggestion makes sense to me.  One approach could be to make the standard OGC service names WFS, WCS WMS protected keywords that must not be used as {instance) names.

**Comment by dblodgett-usgs** [comment]
WFS, WCS, and WMS don't appear in the OGC-API Features or Common. I think what you are getting at is that we wouldn't use `{instance}` names `items` or `coverages`? 

I haven't heard any dissent to this proposal -- any opinions on how this would show up in the draft spec? 

My list would be:

- [ ] 9.2.3 eliminate the requirement that `{instanceID}` be present for collections with a single `{instanceID}`
- [ ] 9.2.2 ensure that the collection metadata is a superset of collection instance metadata.
- [ ] 9.10 describe relationship to OGC-API features as a way to expose available ids as feature collections
- [ ] 9.10 craft json-schema for feature collections of EDR items.
- [ ] 9.10 additional required items query type conformance classes.

Any discussion on this task list?

**Comment by m-burgoyne** [comment]
I have created an example OpenAPI schema that makes Instance an optional feature and I think makes the EDR API a better fit with OGC-API Common see [Optional Instance EDR](https://m-burgoyne.github.io/edr_optional_instance_api.html)

**Comment by tervo** [comment]
Should `/collections/{collectionId}/item` and `/collections/{collectionId}/item/{itemID}` be like in OGC API Features (`/collections/{collectionId}/items` and `/collections/{collectionId}/items/{featureId}` correspondingly)?

**Comment by m-burgoyne** [comment]
My intention when I submitted the last update was for them to behave in the same way and  the fact that it has /collections/{collectionId}/item rather than /collections/{collectionId}/items is a mistake.  I will correct the typing error

**Comment by dblodgett-usgs** [comment]
This issue has been superseded by #28 Will continue the conversation there.
