### ISSUE TITLE
HTTP POST query definition of coordinates

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/Environmental-Data-Retrieval-API#121]
As well as supporting the standard query parameters used by the GET query to define the geo-temporal dimensions, it would also be advantageous if POST queries allowed dimensions to be input in the formats that the **Collection** supported as outputs (i.e. GeoJSON, CoverageJSON, shape etc.).  This could make it easier for the results of one query to be used to define the coordinate bounds of another.

**Comment by dblodgett-usgs** [comment]
Flesh out a discussion about this but note that this is future work and the issue can be closed once we have established a tentative plan.
