### ISSUE TITLE
Change /ats segments in Abstract Test URIs to /conf

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/Environmental-Data-Retrieval-API#124]
Change `/ats` segments in Abstract Test URIs to `/conf`.

See section 3.2 and 5.5 of the [existing OGC-NA policy on specification elements](http://portal.opengeospatial.org/files/?artifact_id=39194).

**Comment by chris-little** [comment]
@ghobona The conformance classes and requirements classes have URIs with /conf and /req respectively. Do you mean all the sub paths, such as /ats/collections/crs84 which points to /req/collections/crs84?

**Comment by chris-little** [comment]
@ghobona @m-burgoyne @dblodgett-usgs Thanks to Mark for that massive editting session.
