### ISSUE TITLE
consider alignment with TestBed16 DAPA

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#125]
The testbed explored retrieval of data using area/cube/timeseries etc. See [OGC DAP API Resource Tree](https://eratosthenes.pvretano.com/Projects/tb16/dapa/)
Engineering Report being produced. 
[EOX's implementation API](http://eurodatacube.com/) used with Jupyter notebooks, so undermining need for WPS. Slight assumption that fields were images because of EO participants. Looking at integration with DGGS too. 

Jupyter also used by [Terradue's implementation](https://github.com/opengeospatial/t16-dapa-terradue-sentinel-5p-NO2).  

Another implementation from [Interactive Instruments](http://t16.ldproxy.net/ghcnd) 

They are all aware of alignment/harmonisation with EDR API.

**Comment by dblodgett-usgs** [comment]
I think this should be closed as future work / won't fix

**Comment by chris-little** [comment]
agreed to close in meeting 35. Details put on examples pages in wiki
