### ISSUE TITLE
Public Comment 00: Add example comparing EDR API with SOS/SWE/O&M

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#127]
@m-burgoyne has agreed to draft an example using the aviation ICAO IWXXM standard which is based on O&M.

The original suggestion came from SWE/STA expert @KathiSchleidt at the [O&M repo Issue 63](https://github.com/opengeospatial/om-swg/issues/63#issue-673363760)

**Comment by KathiSchleidt** [comment]
If people are interesting in doing an alignment between EDR and Air Quality on SOS or STA, I'm willing to support on the SOS or STA side. Endpoints:
STA: https://airquality-frost.docker01.ilt-dmz.iosb.fraunhofer.de/v1.1
SOS: http://luft.umweltbundesamt.at/inspire/sos?service=SOS&version=2.0.0&request=getCapabilities
WFS (Stations for SOS): http://luft.umweltbundesamt.at/inspire/wfs?service=WFS&version=2.0.0&request=getCapabilities

**Comment by chris-little** [comment]
Agreed to close in meeting 35. Details will be put in Examples wiki by @m-burgoyne
