### ISSUE TITLE
Example EDR API endpoints?

### ISSUE THREAD

**Issue by liangsteve** [opengeospatial/Environmental-Data-Retrieval-API#128]
My research group would like to learn more about EDR API.  Is there any example endpoint we can try?  @chris-little ??  Thanks!!  :)

**Comment by dblodgett-usgs** [comment]
Hi @liangsteve -- sorry to be a little slow on the uptake here. 

We have a few examples linked up here: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/OAB-Review but need to put together a more general example implementations list still. 

I'll be opening a new issue to get that going in just a moment.
