### ISSUE TITLE
Create example implementations list.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#129]
Per #128 we need to create a stand along implementations page(s) to document the extent to which each example implements the EDR API.

There is a starter list in: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/OAB-Review

Possible template for describing the implementations here: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/Monitoring-network-mockup

Should make sure this has a prominent link in the README but should implement in the WIKI.

**Comment by dblodgett-usgs** [comment]
Moved the OAB list here: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/Example-Environmental-Data-Retrieval-API-Implementations

Need to flesh out descriptions of each. More discussion needed on exactly what the format should be but this mockup may be worth considering: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/Monitoring-network-mockup

**Comment by chris-little** [comment]
Agreed to close in meeting 35. Details in Examples wiki needs linking to implmentations list
