### ISSUE TITLE
Metadata structures and support

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#133]
What metadata needs to be identified beyond tht required by OGC API-Common Parts Core and Collections? Such as identified in 
[API-Records Issue 42](https://github.com/opengeospatial/ogcapi-records/issues/42)

**Comment by chris-little** [comment]
My first take on what we should consider from API-Records Core:
Properties:
Queryable | Requirement | Description
-- | -- | --
title | M | A human-readable name given to the resource.
description | M | A free-text description of the resource.
keywords | M | A list of keywords or tags describing the resource.
type | M | The nature or genre of the resource.
formats | O | A list of available distribution formats for the resource.
extent | O | The spatio-temporal coverage of the resource.

Query parameters:
Query Parameter | Description
-- | --
bbox | A bounding box.  If the spatial extent of the record intersects the  specified bounding box then the record shall be presented in the  response document.
datetime | A time instance or time period. If the temporal extent of the record  intersects the specified data/time value then the record shall be  presented in the response document.
type | A resource type. Only records of the specified type shall be presented in the response document.
q | A space-separated list of search terms.  If any server-chosen text  field in the record contains 1 or more of the terms listed then this  records hall appear in the response set.

**Comment by dblodgett-usgs** [comment]
Is this documentation or future work?

**Comment by chris-little** [comment]
Agreed to close at meeting 35. This is future work, including alignment with OGC API Records and other APIs.
