### ISSUE TITLE
Public Comment: Should use CIS JSON not CoverageJSON

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#142]
1. Requirement: [General, #] 
General 
2. Implementation Specification Section number: [General, #] 
General 
3. Criticality: [Major, Minor, Editorial, etc.] 
Major 
4. Comments/justifications for changes: [Comments] 
Coverages (which include timeseries, BTW) in OGC are handled by the Coverages WGs, which however have not been involved sufficiently in the development. Maybe as a consequence, it contains incompatibilities as well as substantial duplication of coverage functionality, albeit in an incompatible manner. Re incompatibility, the specification uses CoverageJSON; this has been investigated by the Coverages group and found strongly incompatible with OGC/ISO coverages. Rather, therefore, the JSON encoding of the official OGC/ISO Coverage Implementation Schema (CIS) should have been chosen which ensures, at the same time, coherence of encodings across JSON, RDF, and common binary formats. In the communities, this specification will lead to confusion and isolated, incompatible islands.

**Comment by chris-little** [comment]
The EDR API does not mandate any payload encodings, so that developers are free to offer any of the WCS standardised encodings if they wish. There is at least one production-quality implementation of the EDR API that utilises a WCS server 'under the covers'.
CoverageJSON is recommended, but not mandated, as it has been proven with several implementations to be effective and scalable to large numbers of users and very large amounts of data.
The re-chartered WCS SWG has offered to work on standardising CoverageJSON to acheive, if possible, compatibility with the coverage model, especially since the evolution of JSON-LD to Version 1.1 has removed a technical barrier. It is expected there will still be trade-off between comceptual purity and performance.

**Comment by chris-little** [comment]
== Detailed Responses to Comments

1. Requirement: [General, #] 
General 
2. Implementation Specification Section number: [General, #] 
General 
3. Criticality: [Major, Minor, Editorial, etc.] 
Major 
4. Comments/justifications for changes: [Comments] 
Coverages (which include timeseries, BTW) in OGC are handled by the Coverages WGs, which however have not been involved sufficiently in the development. Maybe as a consequence, it contains incompatibilities as well as substantial duplication of coverage functionality, albeit in an incompatible manner. Re incompatibility, the specification uses CoverageJSON; this has been investigated by the Coverages group and found strongly incompatible with OGC/ISO coverages. Rather, therefore, the JSON encoding of the official OGC/ISO Coverage Implementation Schema (CIS) should have been chosen which ensures, at the same time, coherence of encodings across JSON, RDF, and common binary formats. In the communities, this specification will lead to confusion and isolated, incompatible islands.

5. Disposition: Addressed in current version

6. Response
The EDR API does not mandate any payload encodings, so that developers are free to offer any of the existing WCS standardised encodings if they wish. There is at least one production-quality implementation of the EDR API that utilises a WCS server 'under the covers', and there are multiple implementations that offer WCS supported payloads such as NetCDF and GRIB2.

CoverageJSON is recommended, but not mandated, as it has been proven with several implementations to be effective and scalable to large numbers of users and very large amounts of data using simple clients.

The re-chartered WCS SWG has offered to work on standardising CoverageJSON to achieve, if possible, full compatibility with the coverage model, especially since the evolution of JSON-LD to Version 1.1 has removed a technical barrier. It is expected there will still be trade-off between conceptual purity and performance. The existing community of CoverageJSON users will need to convinced of the benefits of a new version. It is not yet clear whether backward compatibility can be achieved.

**Comment by dblodgett-usgs** [comment]
I'd like to point out that use of CoverageJSON is consistent with  [principle 3](https://github.com/opengeospatial/OGC-Web-API-Guidelines#principle-3---use-well-known-resource-types) "Use Well Known Resource Types". And to a certain extent, principles 2 in that CoverageJSON will allow easier adoption of the API. As and if the CIS-JSON encoding becomes more prominent, there is no reason that it would not be used instead but forcing it at this stage would not be a service to the user community.
