### ISSUE TITLE
Trajectory/Corridor query - Out-of-date usage of the 'time' parameter

### ISSUE THREAD

**Issue by pavol-novotny** [opengeospatial/Environmental-Data-Retrieval-API#147]
The section **`coords`** for the **Trajectory** and **Corridor** query still uses the out-of-date name of the parameter (at several places in the specification): **`time`**. It should be corrected to **`datetime`**.

**Comment by chris-little** [comment]
@pavol-novotny Change on its way. Some 'time's should be left, and not all changed to 'datatime'

**Comment by chris-little** [comment]
@pavol-novotny changes awaiting second review. 'datetime' now only refers to ISO8601 strings. time (not a parameter) used to refer to the general concept or Unix epoch time.
