### ISSUE TITLE
github pages view of the candidate standard?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#15]
Any objection to turning on github pages for the repository so we have an online rendered html view of the spec? 

e.g. https://opengeospatial.github.io/Environmental-Data-Retrieval-API/candidate-standard/EDR-candidate-specification.html

would render the latest merged html

**Comment by m-burgoyne** [comment]
We could also use GitHub Pages to host a swagger-ui view of the swagger docs

**Comment by cportele** [comment]
I think the standard approach is (or at least it was the case 1-2 years ago) that drafts should be on an OGC domain (http://docs.opengeospatial.org/DRAFTS/) and will be autogenerated daily. The generation is controlled by `asciidoctor.json` files in the repo (here is the one from [Features](https://github.com/opengeospatial/ogcapi-features/blob/master/asciidoctor.json) and the associated text in the [README](https://github.com/opengeospatial/ogcapi-features#building)).

**Comment by dblodgett-usgs** [comment]
Do we need to talk to anyone on OGC staff to turn that DRAFTS build on? Looks like we need to create an asciidoctor.json first regardless.

**Comment by cportele** [comment]
@dblodgett-usgs - Just contact Greg and he will set it up.
