### ISSUE TITLE
Trajectory/Corridor query - Confusing paragraph about intersection of the area

### ISSUE THREAD

**Issue by pavol-novotny** [opengeospatial/Environmental-Data-Retrieval-API#150]
The specification of the **Trajectory** and the **Corridor** query contains the following paragraph:
> "Intersects" means that the area specified by the parameter `coords`, includes a coordinate that is part of the (spatial) geometry of the resource. This includes the boundaries of the geometries.

The *area* word in this paragraph also links the section **5.1. area**. It does not make much sense to me. @m-burgoyne Please, can you clarify it?

**Comment by m-burgoyne** [comment]
The link should not have been added, I will remove it

**Comment by chris-little** [comment]
@m-burgoyne please also fix 'Well Know Text' to 'Well Known Text'

**Comment by chris-little** [comment]
@m-burgoyne and also the temporal 'intersects' in datetime

**Comment by m-burgoyne** [comment]
@chris-little where is temporal 'intersects' in datetime?

**Comment by chris-little** [comment]
@m-burgoyne 9.3.1 Shared query parameters. 'datetime'  just before example 2

**Comment by chris-little** [comment]
@pavol-novotny Changes awaiting a second review. Thank you for the quality control and thanks to @m-burgoyne  for working late.
