### ISSUE TITLE
Change spec element URIs to reflect multipart document

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/Environmental-Data-Retrieval-API#151]
During Sprint#2 it was mentioned that Part 2 of the EDR API is already being [planned](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/Future-Work).

That means that:

- The title of the current document must be updated to **OGC API - Environmental Data Retrieval - Part 1: Core**.
- The base of all URIs of specification elements must be changed from `http://www.opengis.net/spec/ogcapi-edr/1.0/` to `http://www.opengis.net/spec/ogcapi-edr-1/1.0/`

TIP: Use a python script (or any programming language) to change the URIs of specification elements.

**Comment by m-burgoyne** [comment]
I have updated the latest pull request (#149) to include fixes for the incorrect URI's

**Comment by chris-little** [comment]
@ghobona We have plans for further work, but whether this is a Part 2 or just version 1.1 of the current version is not yet clear or decided. We can have a quick discussion on Thursday.

**Comment by dblodgett-usgs** [comment]
Can close pending discussion on 11/18

**Comment by chris-little** [comment]
Agreed to close in meeting 35. Part 2 or Version 1.1 of Part 1 is still an open question, but no difficulties envisaged.
