### ISSUE TITLE
Meaning of the 'resolutionx' parameter in the Corridor query

### ISSUE THREAD

**Issue by pavol-novotny** [opengeospatial/Environmental-Data-Retrieval-API#152]
The current description of the `resolutionx` parameter in the EDR specification looks like this:
> A) If the `resolutionx` parameter is provided, denotes the number of intervals to retrieve data for along the path between the minimum and maximum width coordinates
> B) The total number of intervals includes the values for the minimum and maximum coordinates
> C) A `resolutionx` value of 0 MUST return all available data at the native x resolution between the minimum and maximum coordinates
> D) IF `resolutionx` is not specified data should be returned for just the locations specified in the requested coordinates (ONLY IF interpolation is supported by the API)
> `resolutionx = number of intervals`

Paragraphs A) and B) do not sound intuitively to me. I just guess that `resolutionx` in fact means the number of samples along the `X` dimension placed equidistantly to cover the given corridor width where the `X` axis is perpendicular to the central line of the corridor and lies in the horizontal plane. For example, it looks as follows for `resolutionx=5`:
![image](https://user-images.githubusercontent.com/63053940/99316118-14753b80-2864-11eb-8a6e-46962c402c95.png)
(The blue grid is the original data in the horizontal plane in the native resolution, the black line is the central line of the corridor specified by the `coords` parameter and the red dots are the returned samples.)
Is it correct?

My interpretation of paragraph C) is as follows:
![image](https://user-images.githubusercontent.com/63053940/99316301-6b7b1080-2864-11eb-9313-ecb542e80616.png)
Is it correct?

However, I have no idea what is the meaning of paragraph D). What should be returned if `resolutionx` is not specified? Just the samples lying on the central line of the corridor specified by the `coords` parameter? If so, then it seems that the `corridorwidth` parameter has no sense in this case and the result is equivalent to the `/trajectory` data query. Or, am I missing something? 

Moreover, it is quite confusing that this line is placed in the same cell of the table as paragraph D) (that covers a case when the `resolutionx` parameter is not specified):
`resolutionx = number of intervals`
It would be more appropriate to place it into the same cell as paragraph A) or it should be placed into a completely separate cell.

@m-burgoyne What do you think about it? Please, can you clarify these points?

**Comment by m-burgoyne** [comment]
@pavol-novotny,  I agree that the description is not clear and D is incorrect; does the following make more sense?:

A)	If the `resolutionx` parameter is provided, it denotes the number of intervals to retrieve data for along the width of the corridor path including it’s minimum and maximum width coordinates

B)	A `resolutionx` value of 0 MUST return all available data at the native x resolution between (and including) the minimum and maximum coordinates of the defined corridor.

C) IF `resolutionx` is not specified the API SHOULD return all available data at the native x resolution of the source data including the minimum and maximum coordinates of the defined corridor.
 
`resolutionx = number of intervals`

I think the diagrams help to explain the idea a lot more clearly than the text, would you be happy for me to include them in the document?

**Comment by chris-little** [comment]
@m-burgoyne @pavol-novotny I suggest we discuss this at the next WG, Thursday 19 Nov 2020. Supporting A or C or both seems reasonable. C has the advantage of no interpolation, only the use of Bresenham's Algorithm to identify the grid points, so should be lightweight. 
Option A required interpolation, which maya be heavyweight, or even inappropriate for some parameters that have noisy structure, like convective rain.

**Comment by chris-little** [comment]
@pavol-novotny @pete-trevelyan What are the aviation use cases for the corridor? Have the aviation users expressed a preference?

**Comment by pavol-novotny** [comment]
@m-burgoyne Yes, it is a good idea to use those diagrams for illustration, so I will be happy if you include them in the specification. However, I still do not understand the difference between `resolutionx=0` and the case when `resolutionx` is unspecified. I would suggest to change the specification as follows:
* `resolutionx=0` - Return the original data in the native resolution.
* `resolutionx` is unspecified - The optimal resolution is determined by the server itself.

@chris-little I am afraid that the use of Bresenham's Line Algorithm might not be so straightforward in a general case (for corridors in 4D). I think that it only can be applied if the native grid has an equidistant spacing of the grid points along each dimension. However, this is typically not true e.g. for isobaric levels in NWP models. In addition some NWP models have lower resolution of the horizontal grid at the upper levels than at the lower levels. Also the time step might not be the same for the whole covered time range.

I also think that both options A) and C) seem reasonable. For example, if we want to get observational data from all stations close to the flight (METARs), the option C) seems to have more sense. On the other hand, when requesting data from an NWP model, the option A) seems to me to be more appropriate. Another question is, what output formats can be used to store the resulting grid aligned along the corridor. One option is NetCDF. Another option might by CoverageJSON, but it currently does not seem to support a suitable [Domain Type](https://covjson.org/domain-types/) for corridors.

> We could take the same approach that we did for Cube, and remove the parameters and leave it to the server?

@chris-little I am not sure what you mean by this sentence - the Cube query still has the parameters `resolutionx`, `resolutiony`, `resolutionz`. As far as I know, just the parameters for specification of the interpolation methods have been removed.

**Comment by m-burgoyne** [comment]
@pavol-novotny, I am happy with your proposed change:

A) If the `resolutionx` parameter is provided, it denotes the number of intervals to retrieve data for along the width of the corridor path including it’s minimum and maximum width coordinates

B) A `resolutionx` value of 0 MUST return all available data at the native x resolution between (and including) the minimum and maximum coordinates of the defined corridor.

C) IF `resolutionx` is not specified the API SHOULD return all available data at the optimal resolution is determined by the server itself including the minimum and maximum coordinates of the defined corridor.

resolutionx = number of intervals

**Comment by chris-little** [comment]
@pavol-novotny Thank you for pointing out that we still have the same parameters in `Cube`.
@m-burgoyne OK. The cases A, B, C cover the use cases that I suggested. 
I will resume sleeping;-)

**Comment by pavol-novotny** [comment]
Perhaps, specification of the `resolutionz` parameter should be adjusted similarly as the `resolutionx` parameter. @m-burgoyne @chris-little What do you think about it?

**Comment by m-burgoyne** [comment]
@pavol-novotny @chris-little I agree

**Comment by chris-little** [comment]
@m-burgoyne @pavol-novotny will add diagrams and examples to the spec today. when done, issue will be closed

**Comment by pavol-novotny** [comment]
![image](https://user-images.githubusercontent.com/63053940/99679858-b7a09d80-2a7c-11eb-8c83-76281ed30749.png)
A new diagram - C) replaced by B).

**Comment by chris-little** [comment]
Changes now incorporated into a PR awaiting one more review before merge.

@pavol-novotny Outstanding issue: Diagrams for z should have depth/width/height vertical so envelope of corridor is a parallelogram.

**Comment by pavol-novotny** [comment]
@m-burgoyne @chris-little Diagrams for `resolutionz`:
![image](https://user-images.githubusercontent.com/63053940/99732185-53eb9400-2abf-11eb-8640-994104197e07.png)
![image](https://user-images.githubusercontent.com/63053940/99732317-944b1200-2abf-11eb-9dad-a6e9d30ea404.png)

**Comment by chris-little** [comment]
Changes now incorporated into a PR awaiting one more review before merge.

Outstanding issue: Diagrams for z should have depth/width/height vertical so envelope of corridor is a parallelogram.

@pavol-novotny @m-burgoyne Terrific!
