### ISSUE TITLE
14 conformance classes?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#158]
I count 9 -- this needs to be updated on line 8 of clause_2_conformance

**Comment by chris-little** [comment]
@dblodgett-usgs @m-burgoyne I agree less than 14. Queries are altogether. Contents lists 9. I think B6 is separate from B5 to support Features as opposed to Collections stuff.
B.2. Conformance Class Core
B.3. Conformance Class Collections
B.4. Conformance Class JSON
B.5. Conformance Class GeoJSON
B.6. Conformance Class EDR GeoJSON
B.7. Conformance Class CoverageJSON
B.8. Conformance Class HTML
B.9. Conformance Class OpenAPI 3.0
B.10. Conformance Class Queries

**Comment by chris-little** [comment]
@m-burgoyne Cana you confirm that there are EDR GeoJSON requirements extending the common GeoJSON ones? If not we remove and conformance classes come down to @dblodgett-usgs count of 8

**Comment by m-burgoyne** [comment]
@chris-little EDR GeoJSON extends GeoJSON by defining fields that should be in the Properties

**Comment by chris-little** [comment]
@dblodgett-usgs @m-burgoyne So we stay with 9 classes.
