### ISSUE TITLE
License and Access rights

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#16]
We need to consider how License and Access rights information are provided in the metadata responses of the API.

**Comment by cportele** [comment]
Here is what we did in Features:

* The license information of the API is part of the OpenAPI definition.
* On the collection level, we have a recommendation to use the registered `license` link relation type: [/rec/core/fc-md-license](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#rec_core_fc-md-license). Also look at  [example 4](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#example_4).

**Comment by chris-little** [comment]
Added informative text as used in Features, suggested by @cportele  agreed in EDR API SWG 20
