### ISSUE TITLE
EDR Access Patterns in initial and future EDR specifications.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#20]
This issue is meant to elicit discussion. I expect the description to evolve as the scope of each specification version / extension is discussed and decided.

The charter lists initial deliverables in [section 4.1](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/EnvironmentalDataRetrievalAPI-SWG-Charter.adoc#41-initial-deliverables) and a number of additional tasks in [section 4.2](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/EnvironmentalDataRetrievalAPI-SWG-Charter.adoc#42-additional-swg-tasks). There is also an "out of scope" statement in [section 3.2](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/EnvironmentalDataRetrievalAPI-SWG-Charter.adoc#32-what-is-out-of-scope). 

Summarizing the charter, my interpretation is that EDR Patterns will be:
V1 (core?):
- Point or item with n parameters at a time instant.
- Point or item timeseries with n parameters.

V2 (sampling geometry?):
- Simple vertical profile for a time instant.
- Rectangular subset / tile.
- Polygonal subset / tile.

V3 (trajectories and corridors?):
- Samples along a 2-4 dimensional trajectory
- Subsetting information within a 2-4 dimensional corridor around a trajectory.

V4 (ensambles?):
- Support for ensemble EDR collection instances.

**Comment by chris-little** [comment]
I agree with your interpretation of the Charter. that was the intent of the the Charter.

I envisage some things may swap around  beteween V2 and V3, depending on implementation experiences.

**Comment by dr-shorthair** [comment]
Important access pattern would be to retrieve observations/time-series associated with a named feature (e.g. monitoring station, scene, transect, borehole). 
i.e. geometry not the only key
