### ISSUE TITLE
Document EDR Geometry

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/Environmental-Data-Retrieval-API#26]
Users of this standard may not be familiar with the underlying geometry concepts. The API is hard to grasp without that knowledge. An informative annex documenting the EDR geometries and showing their relation to the 2.5-D geometry we know and love would be useful.  Plus, these geometries may be useful to others.

**Comment by dr-shorthair** [comment]
https://www.academia.edu/2872011/Climate_Science_Modelling_Language_standards-based_markup_for_metocean_data ;-)

**Comment by chris-little** [comment]
Agreed EDR API SWG #11

**Comment by dblodgett-usgs** [comment]
The agreement here was that we will document the use of geometry and a particular issue for it is not needed at this stage.
