### ISSUE TITLE
Time syntax in Trajectory

### ISSUE THREAD

**Issue by percivall** [opengeospatial/Environmental-Data-Retrieval-API#27]
EDR Trajectory:
> The trajectory query supports the Linestring Well Know Text (WKT) geometry type, the trajectory query SHOULD support 2D, 3D and 4D queries allowing the definition of a vertical level value (z) and an time value (as an epoc time) therefore coordinates for geometries may be 2D (x, y), 3D (x, y, z) or 4D (x, y, z, t).

- WKT does not specify a syntax for t.  Need to specify what EDR will use for t syntax.
- consider a format for time like ISO 8601 
- consider the approach Moving Features to define a trajectory: specify a start time for the boundary, then t instances are offsets
- allow 3D(x,y,t)
- change "epoc" to "epoch"

> [7.1 mf:MovingFeatures](http://docs.opengeospatial.org/is/18-075/18-075.html#15 )

> 7.1.3.1 mf:sTBoundedBy

> This element regulates the spatio-temporal region where the trajectories described in the foliation exist. Times used in trajectories are described in offset time, that is, duration in seconds or minutes or hours from the time origin defined here is shown in the trajectory elements. The mf:STBoundedBy element inherits gml: BoundingShapeType, and include gml:EnvelopeWithTimePeriod [OGC 07‑036].

**Comment by chris-little** [comment]
@percivall As discussed in telco, IETF RFC3339, a restrictive profile of ISO8601, for timestamp, would be a good reference. with the proviso that the RFC is very nuanced, and studiously makes no mention of subtracting two time stamps to get a valid duration. In fact, I do not think it allows the comparision of two timestamps from different computers.

**Comment by chris-little** [comment]
Corrected epoc to epoch.

**Comment by chris-little** [comment]
IETF RFC 3339 is added to the references.

**Comment by chris-little** [comment]
The approach adopted by Moving Features is a proper CRS way: specify an epoch and a number of UoMs from the epoch. This is an approach very familiar to the Met Ocean communities: forecasts are routinely timestamped by origin plus number of hours or days, such as T+36 (hours) from 2020-03-19T12Z.

It seems likely that RFC 3339 will be used for some patterns, and epoch plus number of UoMs for the Trajectory pattern.
