### ISSUE TITLE
How does EDR relate to THREDDS catalogs?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#33]
This is a bit of a leading question but I think it is instructive.

A very common mechanism for provision of EDR-type data is the THREDDS catalog -- a metadata layer over a server's data holdings that provides a number of access methods for datasets.

e.g. https://thredds.ucar.edu/thredds/catalog/grib/NCEP/RTMA/CONUS_2p5km/catalog.html?dataset=grib/NCEP/RTMA/CONUS_2p5km/TP

Provides OPeNDAP, WCS, WMS, NetcdfSubset, etc. Do we expect that an EDR api could be added to the access list of a given THREDDS catalog?

**Comment by chris-little** [comment]
@dblodgett-usgs My first thought is that the EDR API is the, or part of the, access API from the THREDDS catalog to the underlying  OPeNDAP, WCS, WMS, NetcdfSubset, etc. Well perhaps not WMS, unless the pixel orientated getInfo is implemented.
But it depends on the granularity of the THREDDS service - is it dataset, or data value, orientated? Or even both?
For example, NetCDF is undoubtedly one of the most successful scientific data formats and underlying model, but still requires significant learning from any developer.
Without understanding what the THREDDS Access List implies, I thinbk my answer is yes.

**Comment by dblodgett-usgs** [comment]
I think I see where you are going with this, @chris-little There is the issue of granularity -- but I think that is a bit of a separate issue. Note that my example above is actually a large collection of `.grib2` files aggregated together into a virtual dataset. [See here for the complete set of files](https://thredds.ucar.edu/thredds/catalog/grib/NCEP/RTMA/CONUS_2p5km/catalog.html) 

Each of those files has a list of access types (one of which could be an EDR service) and the virtual dataset collection, similarly, could have an EDR service. This puts EDR at the same level as OPeNDAP or WCS as a distribution method for a dataset.

If this is the case, I think we should consider that our initial EDR work applies to one dataset in the sense of a dataset in a THREDDS catalog ( a file or some virtual aggregation of files or other content ). Reinventing the catalog wheel for these dataset aggregates seems like something we don't want to tackle, but adding to the canon of access types for these datasets is absolutely what we want to do.

**Comment by chris-little** [comment]
@dblodgett-usgs "EDR at the same level as OPeNDAP or WCS " Agreed.

"as a distribution method for a dataset" may be precisely correct, but I want to avoid being bogged down in taxonomic theological debates. I would rather that we push ahead with EDR and 'ask permission' later, and then let the ontologists figure out  what we did.

**Comment by dblodgett-usgs** [comment]
100% agreed -- I opened this issue to do just that; Avoid unexpectedly entering the debate over whether EDR supports multiple datasets or not. This means that we can focus EDR API efforts on distribution of a single dataset. We should add a note that an EDR API instance distributes one and only one dataset and that "collections" (if that's what we end up calling them) and "instances" are meant to be thematic views (or some such description) of the dataset.

**Comment by chris-little** [comment]
With provisos around the definition of a dataset too! ;-)
