### ISSUE TITLE
Should we add all Charter Members as Submitters?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#34]
Here is the list of Charter Members of the EDR API SWG:
|Chris Little     |UK Met Office
|Steve Olson      |US National Weather Service
|Frédéric Guillaud|Météo-France
|Dave Blodgett    |US Geological Survey
|Tom Kralidis     |Meteorological Service of Canada
|Roope Tervo      |Finnish Meteorological Institute
|Bruce Bannerman  |Individual
|Chris Lynnes     |NASA
|Ethan Davis      |UCAR
|Cristiano Lopes  |ESA
|Iain Burnell     |DSTL
|Keith Ryden      |ESRI
Should we add all of them, or their institutions, as submitters (not necessarily editors) of the Candidate Specification?

**Comment by dblodgett-usgs** [comment]
I would say they should also participate at some level in the SWG. As long as they all have, then yes.

**Comment by chris-little** [comment]
Some have declined because of lack on involvement. Those who agreed have been added.
