### ISSUE TITLE
Develop conformance tests for the EDR API

### ISSUE THREAD

**Issue by StephanSiemen** [opengeospatial/Environmental-Data-Retrieval-API#35]
To support the development of EDR services and clients it would be great to start the development of tools and a suite of conformance tests for the new standard. This should also help with the development of the new standard. **Please indicate in this issue if you have interest to contribute to this or have relevant work/solutions which should be considered here.**  

Tests should cover the interaction and responses of a EDR service. Beside a test suite for the conformance of the server (which might be integrated with CITE) tools to test the responses are correct formatted will be helpful.

**Comment by chris-little** [comment]
I have been constructing a PR including the Annexe A of the Abstract Test Suite. 
I have yet to state the tests that are specific to the query patterns. Which of all those query requirements need tests and how should they be structured? For example, is it enough to have one test that all query coordinates must adhere to WKT, or should each pattern be separate? Or do we wish to be stricter or more liberal than the WKT standard?

**Comment by chris-little** [comment]
We now only need to add to the standard tests for the EDR specific query patterns.

Most of the tests would be to state that the queries and their parameters adhere to their API formal definition in OpenAPIv3 YAML schemas.

A more concrete example from Pete Trevelyan: 
1. The positions of all the data points returned in the payload in response to an Area query must lie within the specified Area polygon

From me:
2. The time and vertical coordinates of the data returned in the payload must correspond to the time and vertical coordinates, or lie within the time range and vertical range, specified for the query.

3. The positions of all the data points returned in the payload in response to a Position query must lie within the specified or default radius around the specified Position.

4. The positions of all the data points returned in the payload in response to a Trajectory query must correpsond to the horizontal, vertical and temporal positions specified in the Trajectory query.

5. The positions of all the data points returned in the payload in response to a Corridor query must lie within the specified  horizontal, vertical and temporal boundaries specified in the Corridor query.

Is this enough??

**Comment by chris-little** [comment]
There are now abstract test suites covering the conformance classes of the standard. The queries all have schema snippets for validation of parameters and documented responses.

Is this enough?

**Comment by chris-little** [comment]
Agreed to open more specific issues as required. EDR API SWG21
