### ISSUE TITLE
Changes to spec by unknown user?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#37]
@m-burgoyne do you maybe have something wrong with your local git user configuration? There's a user showing "Media" with no known github presence that came in through your recent PR. Would be very helpful to have clear change history of who is making these changes...

https://github.com/opengeospatial/Environmental-Data-Retrieval-API/pull/32/commits/f384b86b66ccb03beaaea0edccf4ca191c8446cf

**Comment by m-burgoyne** [comment]
@dblodgett-usgs, sorry it was an error my local git user configuration

**Comment by dblodgett-usgs** [comment]
OK -- no problem. Probably not worth trying to rewrite history, I just saw that and was real confused.
