### ISSUE TITLE
Should we keep our draft OpenAPI doc up to date?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#43]
There is an older OpanAPI html in `docs` (https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/docs/edr_api.html)

@m-burgoyne do you want to keep that up to date or remove? I would be in support of updating it and linking in the README but maybe others have issue with using the github.io for any semi-official SWG artifacts?

**Comment by m-burgoyne** [comment]
@dblodgett-usgs I will correct it to point at the master branch.  I think it makes it a lot easier for people to review any changes than having to read the raw JSON or YAML

**Comment by chris-little** [comment]
Agreed at EDR API SWG #11

**Comment by dblodgett-usgs** [comment]
fixed in bec20c3d9f8aedb7d7f6d89fcc335d222219bd18
