### ISSUE TITLE
Should there be 2 levels of returned metadata: basic & extended/verbose?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#44]
Some of the metadata returned in current implementations is very complex and detailed and maybe off-putting to non-expert users. Should we hide some of it completely from API users?

**Comment by dblodgett-usgs** [comment]
I'm in support of this proposal.

I think we should allow access to a complete set of information for users who want to build more advanced systems.

**Comment by ShaneMill1** [comment]
There are a few things to consider when looking at existing implementations:

**Existing Implementation Observation**
Looking at the NWS implementation: https://data-api.mdl.nws.noaa.gov/EDR-API:
Assuming that you are not using the search engine, you can start in "groups" and follow the links down the structure of the API until you reach the client where you make the query. 

- As you move down the structure of the API, metadata is offered at some points along the way but the majority of the metadata is exposed in two places, at the point of making the query and once you make the query and return the data:

Point of making query:  
https://data-api.mdl.nws.noaa.gov/EDR-API/collections/automated_gfs_100_forecast_time0_lat_0_lon_0_Entire_atmosphere_considered_as_a_single_layer/instance/00z?outputFormat=application%2Fjson

Once you have made the query:
https://data-api.mdl.nws.noaa.gov/EDR-API/collections/automated_gfs_100_forecast_time0_lat_0_lon_0_Entire_atmosphere_considered_as_a_single_layer/instance/00z/point?coords=POINT(-87.962243%2041.543411)&parametername=RH_P0_L200_GLL0&time=2020-04-08T00:00:00/2020-04-09T00:00:00&outputCRS=EPSG:4326&interpolation=nearest_neighbor&outputFormat=CoverageJSON

Another note, once you have made the query, the output format will also decide how much metadata is provided _with_ the data. CoverageJSON returns metadata with data as do many other output formats, but CoverageJSON is luckily pretty succinct. I think following different output format schemas will dictate how much metadata you provide in the actual output to a certain extent.
For example, looking at the metars endpoint, IWXXM returns more metadata than CoverageJSON. 

So in summary here, after the query, I think the amount of metadata provided depends on the output format although you could in theory supply a query parameter for metadata provided as basic or extended/verbose. Definitely a valid argument to make. Before the query, I think there probably needs to be a specific structure in the metadata being provided.

**Related Search Engine - Metadata aspects**
Then, you add the search engine aspect of things that relies on metadata to perform a search. However, in related issue #40, if we choose to follow opensearch geo and time, we can keep the exposure to metadata at a minimal, and supply only the links to the point of making the data query, so the only true metadata exposure is right before you make the data query and once you make the data query. In the current implementation of the search engine, a link to the actual csw record that contains the metadata the search engine relies on is exposed as well, but it doesn't necessarily need to be.

**Comment by dblodgett-usgs** [comment]
@ShaneMill1 -- I think the last thing you said there is really important. This comment is a little off topic, but I want to tease this out a bit. Sorry to hijack.

> ... we can keep the exposure to metadata at a minimal, supply only the links to the point of making the data query, so the only true metadata exposure is right before you make the data query and once you make the data query. In the current implementation of the search engine, a link to the actual csw record that contains the metadata the search engine relies on is exposed as well, but it doesn't necessarily need to be.

I like this pattern of using an opensearch API to access a catalog of EDR query endpoints -- putting the discovery metadata (harvested out of the query endpoint) there. It gives an implementer a flexible way to provide search over a large number of datasets tailoring the metadata profile to an intended user or type of catalog client. I think that is more-or-less out of scope for the EDR spec, but clearly in scope for a best practice?

Coming to, as you say, "the point of making the data query" -- which I take to be what we are currently calling the EDR collection endpoint which returns "EDR collection metadata". Thinking in terms of simplifying what we are doing with collections -- removing them from EDR API as I've proposed in #38. (I swear I'm getting back on topic) What if the landing page contained a default lightweight metadata profile that would be of interest to a web-crawler and we had some kind of EDR-metadata end point off the landing page that would provide extended metadata for clients who want to go grab it? 

A dedicated metadata endpoint could provide a number of metadata profiles. Our current EDR collection metadata would be what we'd put in the spec as required. The landing page could align with something like [science-on-schema.org](https://github.com/ESIPFed/science-on-schema.org) that would have a lot of utility there and not scare people off. A dedicated metadata endpoint would give a bunch of flexibility to do whatever is needed for rich metadata via various profiles.

This would work if we keep "collection" to mean EDR dataset, but why do we need the extra level of complexity of having a metadata catalog of datasets (and the discovery hooks/hypermedia that requires)? Why not just have an EDR API describe the metadata for a dataset it offers on its landing page and let people jump into the details from there. The approach you are using with the Opensearch catalog is already going that direction by bypassing the landing page and hooking up to the collection end point, right?

**Comment by adamml** [comment]
Coming into your discussions here, so I apologise if I'm missing some subtleties. I think the point @dblodgett-usgs makes here is really important:

> A dedicated metadata endpoint could provide a number of metadata profiles. 

Getting a Schema.org based landing page - maybe even pulling from the endpoint(s) has great benefits for interoperability and discoverability, because as he notes the lightweight structured metadata could be harvested by a search engine.

If some low-level of aggregation of metadata is needed, the Schema.org could point via a DatasetCatalog to something else, but this seems to be only one level-deep for now (if you follow Schema strictly, unlike with DCAT).

There's some good work around Schema.org ongoing in the Research Data Alliance [Research Metadata Schemas WG](https://www.rd-alliance.org/groups/research-metadata-schemas-wg) as well.

One question I would have is if a standard like EDR should stick to using the base Schema.org encoding, or if adopting the science-on-schema extensions is ok in the spec.

**Comment by dblodgett-usgs** [comment]
I think we should stick to things available from schema.org if we put anything specific in the spec. Science-on-schema.org doesn't extend schema.org much if at all here: https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md Are there specific extensions you are talking about?

**Comment by adamml** [comment]
@dblodgett-usgs That was my mis-remembering what ESIP are doing! I had a memory, probably incorrectly, of it being more like bioschemas where they were extending the base, rather than profiling it.

**Comment by chris-little** [comment]
@dblodgett-usgs @ShaneMill1 @adamml I think we are agreed that there should be two levels of metadata: simple, that allows the API to be discovered and used, and schema.org is a good way to go. e.g where can I get weather/ocean/hydrology data, and what is its geographics and temporal extent? Second level is the possibly complex, detailed metadata for sophisticated users or developers who wnat to know if the returned data is fit for purpose etc. A number of frameworks could be feasible and supported (WMO WIS Core Profile1.3, IHO, CF-NetCDF,....
