### ISSUE TITLE
Time vs vertical dimension in data queries

### ISSUE THREAD

**Issue by pavol-novotny** [opengeospatial/Environmental-Data-Retrieval-API#45]
I wonder why time and vertical dimensions are treated in a completely different way in EDR data queries:
* For the time dimension there is just a single parameter `time` used for each data query and it can be used for a **single time instance** as well as for a **time interval**.
* On the other hand, for the vertical dimension, the related parameters differ from query to query:
  * `/cube` - parameters `minz`, `maxz` (to specify a vertical range)
  * `/area` - parameter `z` (to specify a single level)
  * `/position` - no parameter to specify a vertical range or a single level (just the parameter `interpolationz` is available)

For the `/position` query, handling of the vertical dimension is quite unclear. In the PDF document *EDR_Candidate.pdf* there is Example 10 containing multiple locations with specified heights:
`coords=MULTIPOINT -77.02 38.94 72.3),(-3.50 50.72 36.35),(1.43 43.63 135.63),(117.23 39.13 10.04),(144.96 -37.80 33.83`
This seems to indicate that the vertical dimension is supposed to be specified within the parameter `coords`. On the other hand, the *EDR_OpenAPI* documentation does not include such an example containing 3D points in the parameter `coords` at all. As the PDF document seems to be a little bit out of date I guess that the above mentioned example is obsolete and it is really intended to use just 2D points in the parameter `coords`. And an extra parameter `z` is just accidentally missing for the `/position` query in the *EDR_OpenAPI* documentation. Is my understanding correct?

From the user's perspective I think that it would be more convenient if the time and vertical dimensions were treated in a similar way. I would suggest to make the parameter `z` work analogically to the parameter `time`, i.e. it could be a single level like `1000` as well as a vertical range like `1000/850` (for data queries `/cube`, `/area` and `/position`). Even unbounded intervals like `../850` or `850/..` could be supported. This way the user could retrieve a vertical profile using the `/position` data query or get data for multiple levels above an area using the `/area` data query.

What do you think about it?

**Comment by dr-shorthair** [comment]
Strictly, the terminology is 
- [Time Instant](https://www.w3.org/TR/owl-time/#time:Instant)
- [Time Interval](https://www.w3.org/TR/owl-time/#time:Interval)
and [Time Position](https://www.w3.org/TR/owl-time/#time:TimePosition) is used for the actual coordinate

See https://www.w3.org/TR/owl-time/ which is an OGC Standard.

**Comment by pavol-novotny** [comment]
@m-burgoyne Please, can you clarify if the 3D points are really intended to be specified in the `coords` parameter of the `/position` data query? Or, is the `z` parameter (similarly to the `/area` data query) just accidentally missing in the *EDR_OpenAPI* documentation?

**Comment by m-burgoyne** [comment]
@pavol-novotny Yes the 3D points are intended to be specified in the `coords` parameter of the position data query.  The reason for splitting out the `z` parameter in the `area` data query is to force the API to only support requests for a single level per polygon,  otherwise there is nothing to prevent a user inputting a different `z` value for each point in the WKT polygon definition.

**Comment by iandruska-ibl** [comment]
@m-burgoyne In that case the essential difference between the `position` query and `trajectory` query is in how the time dimension is treated:

`position` query retrieves the same "trajectory" for multiple time instants:
t1: (x1 y1 z1), (x2 y2 z2), ...
t2: (x1 y1 z1), (x2 y2 z2), ...
t3: ...
...

`trajectory` query retrieves single trajectory which is "stretched" in time:
(x1, y1, z1, t1), (x2, y2, z2, t2), ... 

Is my understanding correct?

**Comment by m-burgoyne** [comment]
@iandruska-ibl  The intention is  `/position` queries return data for discreate locations for the defined time instant or time range they are not intended to be a trajectory or related to each other and any interpolation will be to return the best values for the requested location/times.  
As you say the  `/trajectory’ (and `/corridor`) query retrieves defines the coordinates (x1, y1, z1, t1), (x2, y2, z2, t2), … where the user defines the path that they want to derive data for.

If we change the resolution parameters approach suggested a vertical profile could be requested using the `/trajectory` query in the (x1,y1,**z1**,t1),(x1,y1,**z2**,t1) with a resolutionz=_zintervals_

**Comment by pavol-novotny** [comment]
@m-burgoyne How can I request a vertical profile for a single 2D point and for **all available levels** (instead of requesting sampling along the vertical dimension)?

**Comment by iandruska-ibl** [comment]
@m-burgoyne Now with the `resolution` parameter (https://github.com/opengeospatial/Environmental-Data-Retrieval-API/issues/47#issuecomment-618351382), the `trajectory` query makes sense to me. Without the `resolution` parameter the only option would be to return return values for the exact locations specified in the trajectory. This would be not much different from `position` query.

**Comment by m-burgoyne** [comment]
@pavol-novotny I think it would be a collection business logic decision, but it could be based on the concept that the user would specify a resolutionz value that was the same as the number of available levels.

**Comment by m-burgoyne** [comment]
@pavol-novotny @iandruska-ibl @chris-little, We could implement the concept that a resolution value (resolutionx, resolutiony, resolutionz etc) of **0** would mean return data at the native resolution of the underlying data between the maximum and minimum query request coordinates.  

Not specifying a resolution value would mean just return data for the requested coordinates.

**Comment by pavol-novotny** [comment]
@m-burgoyne I am a little bit confused by your latest comment. Is it actually related to the `/trajectory` query? My current understanding is that there will be just a single `resolution` parameter (to define the number of samples along the trajectory) - i.e. not three parameters `resolutionx`, `resolutiony`, `resolutionz` mentioned by you.

In addition, I am not sure if I understand your suggestion regarding the resolution value of **0**. In general, the trajectory segment might not cross any data point in the native resolution exactly - even the trajectory end points might not lie in data points.

Suppose that we have a 3D grid where the data is located in integer numbers (for each dimension) and we query the data for the following trajectory:

A) `coords=LINESTRINGZ(0 0 0, 15 20 25, 15 20 30)`
The following data points would be crossed by the trajectory:
`(0 0 0)`, `(3 4 5)`, `(6 8 10)`, `(9 12 15)`, `(12 16 20)`, `(15 20 25)`, `(15 20 26)`, `(15 20 27)`, `(15 20 28)`, `(15 20 29)`, `(15 20 30)`

B) `coords=LINESTRINGZ(0 0 0, 29 31 37)`
The only data points crossed by the trajectory would be its end points `(0 0 0)`, `(29 31 37)`.

C) `coords=LINESTRINGZ(0.1 0.1 0.5, 0.9 0.9 99.5)`
No data points would be crossed by the trajectory.

D) `coords=LINESTRINGZ(0.5 0.5 0, 0.5 0.5 100)` - i.e. a vertical profile at 2D point (0.5 0.5)
No data points would be crossed by the trajectory.

Is my interpretation of your suggestion correct? Please, can you clarify it?

**Comment by m-burgoyne** [comment]
@pavol-novotny Sorry the statement was meant as an approach to answer the previous question 

`How can I request a vertical profile for a single 2D point and for all available levels (instead of requesting sampling along the vertical dimension)?`

As the resolution parameters are optional not specifying them would mean just return data for the requested locations.

The concept is that the API definition states that if a user specifies a resolution of `0` the API will return all valid data at the native resolution of the data source between the minimum and maximum coordinates specified (along the specified resolution axis), if this means that there are no valid data values the API would return a 404 error.

**Comment by pavol-novotny** [comment]
@m-burgoyne I still do not understand if there will be just a single `resolution` parameter or multiple resolution parameters (`resolutionx`, `resolutiony`, `resolutionz`) for the `/trajectory` query. Please, can you clarify it?

I am trying to explain that the *native resolution* is quite tricky for trajectories. What would be the expected result for the example D) from my previous comment?
> D) `coords=LINESTRINGZ(0.5 0.5 0, 0.5 0.5 100)` - i.e. a vertical profile at 2D point (0.5 0.5)

Note that the trajectory representing a vertical profile does not really cross any data point. However, do you actually expect that the sampling will be done according to the native resolution in the direction of the `z` dimension? I.e.:
`(0.5 0.5 0)`, `(0.5 0.5 1)`, `(0.5 0.5 2)`, ... `(0.5 0.5 99)`, `(0.5 0.5 100)`

**Comment by m-burgoyne** [comment]
@pavol-novotny, In your example if the user has only specified that `resolutionz=0` I would expect the API to return all of the available levels

(0.5 0.5 0), (0.5 0.5 1), (0.5 0.5 2), ... (0.5 0.5 99), (0.5 0.5 100)

But looking at your example I agree it does not make sense for `resolution`, `resolutionx` and `resolutiony` to behave in the same way.
So my modified suggestion is that the `0` value infers to return all native values only applies to the `resolutionz` query parameter

**Comment by pavol-novotny** [comment]
@m-burgoyne I have opened a new issue #53 to follow up this trajectory related discussion, because my original question in this issue was about the `z`, `minz` and `maxz` parameters in the `/cube`, `/area` and `/position` data queries.

**Comment by chris-little** [comment]
@pavol-novotny To answer the original question 
> why time and vertical dimensions are treated in a completely different way in EDR data queries:
One answer is that traditionally, different syntaxes have been widely adopted for the different Time and Vertical coordinate. 

We do not say that the next EDR API SWG telco will occur in 4 020 Unix seconds, byut 67 minutes, or that I am sitting 10m+1/8 fathom+2 inches above my garden. ;-)

**Comment by pavol-novotny** [comment]
@chris-little In fact, my primary question was not focused on the exact syntax, but rather on the fact that we allow the `/position` and `/area` queries to extend along the `time` dimension but not along the `z` dimension. Why a **time series** is natively supported by the `/position` query, whereas a **vertical profile** is supposed to be queried using the `/trajectory` query? One could say that a time series is also just a special case of a trajectory like this:
`coords=LINESTRINGM(10 20 1588291200, 10 20 1588377600)`

**Comment by dr-shorthair** [comment]
Nicely put @pavol-novotny 

It is an understandable simplification, as there are many many time-series from stations and sensors across a wide range of science domains, while vertical profiles are probably limited to a much smaller user community. And there is the traditional bias to manage time different to space. 

But I agree with your general proposition.

**Comment by chris-little** [comment]
@pavol-novotny I agree too - I would expect a z coordinate in many domains to be usefully specified as a single level or a layer, analogous to instant and time interval. This is very conveneint for gridded data and valid for some observational data at an appropriate (large scale) resolution. This would be a valid query for a Position. We need a separate tightly-scoped issue to discuss whether it should be incorporated for the Area query.
Using a trajectory vertically is also a valid use case, as a meteorological radio-sonde ascent, or an oceaanographic bathy-thermograph descent deviate from the vertical significantly and this may be important for some uses. I propose that this is just a 4D trajectory, and handled by that type of query.
@m-burgoyne @iandruska-ibl @pavol-novotny I support z being like t: point and range both supported.

**Comment by pavol-novotny** [comment]
> Using a trajectory vertically is also a valid use case, as a meteorological radio-sonde ascent, or an oceaanographic bathy-thermograph descent deviate from the vertical significantly and this may be important for some uses. I propose that this is just a 4D trajectory, and handled by that type of query.

@chris-little I do not think that these are good examples of the `/trajectory` query. Note that in a case of the `/trajectory` query the **user specifies the entire trajectory**, along that he or she needs to get the values of the given parameters. On the other hand, in a case of a meteorological radiosonde ascent, the user **does not know the entire trajectory**, just the position of its starting point. Perhaps, such data might be retrieved by the `/radius` query supposing that the given radius is big enough to include the whole trajectory of the radiosonde - however, it could be used just if the `z` parameter was supported for the `/radius` query, as well (it is not included in the current specification).

**Comment by m-burgoyne** [comment]
@pavol-novotny @chris-little The `/radius` query is intended to be a 2D spatial and time query only, if it has a z query parameter it will purely be for identifying a single level.  
We must be careful, the EDR was originally intended as a simple interface following an 80/20 rule for functionality.  Overloading the queries for use cases which are of interest to only a portion of the target audience is in danger of discouraging use of the API by the general development community.  Position and Radius queries are very popular and 90% of the use cases for this type of query only work in a 2D spatial domain (with optional time dimension) with no concept of a height at all.

**Comment by chris-little** [comment]
EDR API SWG #11 agreed:
Position (x,y) can have a z option: single value or 'All'.

Radius around a Position is an alternative form of Bounding Box, convenient for some use cases. It can have a z option: singel value or 'All'.

Area can have a z option: single value or 'All'

Cube can have a z option: single value, range between two values.

Trajectory and Corridor have z multiple values intrinsic to their definitions.  They do not have a range or 'All'
