### ISSUE TITLE
Extent for each parameter separately

### ISSUE THREAD

**Issue by iandruska-ibl** [opengeospatial/Environmental-Data-Retrieval-API#46]
In the query metadata example at https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/examples/position_query_metadata_JSON_gfs.adoc, space-time extent is reported for each parameter separately. I am afraid that this might cause trouble in production.

For instance, a METAR collection can easily expose 20 parameters. If the underlying database contains METAR data for several years, metadata response will be tens of MB long (in extreme cases even hundreds of MB). Even the process of building the extent for each parameter could be quite resource consuming (20 database queries for each parameter vs 1 query for the collection as a whole).

I believe that in the vast majority of real world cases parameter extents will be identical anyway. To me it seems enough to report extents only on the collection level. Or am Is missing some rationale behind?

**Comment by m-burgoyne** [comment]
I agree that just repeating the same information would be very inefficient both in generating the information and consuming it.  I think changing that section to be optional  i.e. only provide it if it differs from the information at collection level would be more sensible.

**Comment by m-burgoyne** [comment]
Data response schemas define the extent section of parameter as an optional property.
