### ISSUE TITLE
Meaning of the 'interpolation' parameter in the '/corridor' data query

### ISSUE THREAD

**Issue by pavol-novotny** [opengeospatial/Environmental-Data-Retrieval-API#47]
I wonder what is the meaning of the `interpolation` parameter in the '/corridor' data query. The *EDR_OpenAPI* documentation says:
> This defines the algorithm that identifies the best data match for the requested location

However, there is also the `interpolationwidth` parameter composed of **interpolation resolution** and **interpolation method**. My interpretation is that this interpolation method should be used for interpolation in the horizontal plane. If so, what is the purpose of the above mentioned `interpolation` parameter?

A related issue is how the sampling along the trajectory (centre of the corridor) is intended to be specified. Similarly to the **interpolation resolution** that is the first component of the parameters `interpolationwidth` and `interpolationz` I would expect another parameter to specify the resolution along the trajectory. Perhaps, the `interpolation` parameter is intended to be used for this purpose? @m-burgoyne Please, can you clarify this? Note that there is a question if the resolution should be specified for each segment of the trajectory separately, or a single resolution should be specified for the entire trajectory.

**Comment by m-burgoyne** [comment]
@pavol-novotny you are correct in your analysis of what the interpolation parameter was intended for, the aim was to allow the definition of the resolution along the specified path.  

It might be best to have a single resolution for the entire trajectory.  If there was a requirement to have different resolutions for each segment it would reduce the complexity of the API interface if the user split the trajectory into seperate requests for each segment, although this would increase the users overhead.

**Comment by pavol-novotny** [comment]
@m-burgoyne So, your idea is that the structure of the `interpolation` parameter should be the same as for `interpolationwidth` and `interpolationz`? I.e.:
`interpolation=R{interpolation resolution}/{interpolation method}`
That would solve specification of the **resolution** along the trajectory. However, what would be the meaning of *interpolation method* in this case? I can imagine that it might be used for time interpolation in case of corridors running over a time range (i.e. `coords` defined by `LINESTRINGM` or `LINESTRINGZM`). Is this the intended usage? If so, what about the other types of corridors (i.e. `coords` defined by `LINESTRING` or `LINESTRINGZ`)?

**Comment by m-burgoyne** [comment]
@pavol-novotny, yes the structure of  the `interpolation` parameter shoud be the same as for `interpolationwidth` and `interpolationz`.  The meaning of _interpolation method_ should be defined in the metadata (i.e. using a link to an explaination of the interpolation approach), _interpolation method_ is just a label.

**Comment by pavol-novotny** [comment]
@m-burgoyne It seems that I did not express my idea quite clearly in my previous comment. My question about the meaning of the *interpolation method* was not about the interpretation of its string value like _linear_ or _nearest-neighbour_. I am asking about the dimension for that this *interpolation method* is specified. My understanding is that the *interpolation method* in the `interpolationwidth` parameter should be applied to the horizontal plane and the *interpolation method* in the `interpolationz` parameter should be applied to the vertical dimension. The *interpolation method* in the `interpolation` parameter might by applied to the time dimension in a case of corridors running over a time range. However, I wonder what should be its purpose in the other types of corridors.

For example, if we have a 2D corridor (the entire trajectory at the same time), we only need to specify the *interpolation method* in the horizontal plane. I guess that it is given by the second component of the `interpolationwidth` parameter (e.g. *bilinear*). But I do not understand what dimension should the second component of the `interpolation` parameter be applied to. Please, can you clarify it?

**Comment by m-burgoyne** [comment]
@pavol-novotny, `interpolationwidth` and `interpolationz` are intended to allow the API user to define the resolution of the returned data for corridor width and height respectively.  I now understand the problem you have identified, the `interpolation` query parameter did not take into account that for both `/corridor` and `/trajectory` this will almost always require interpolating along x, y and t dimensions.  To keep the API as simple as possible it may be worth removing the `interpolation` query parameter, leaving it hard coded as part of the collection business  logic as to what (if any) interpolation is used to map the data values to the requested path.

**Comment by pavol-novotny** [comment]
> To keep the API as simple as possible it may be worth removing the `interpolation` query parameter, leaving it hard coded as part of the collection business logic as to what (if any) interpolation is used to map the data values to the requested path.

@m-burgoyne I am not sure if I understand what you mean. Do you suggest to remove the `interpolation` parameter completely? And the `interpolationwidth` and `interpolationz` parameters, as well? It means that the resolution along all three axes of the corridor would not be controlled by the user, but rather automatically estimated by the collection business logic? Or, do you actually mean to remove just the *interpolation method* component from those parameters and keep the option to specify the resolution by the user? In the latter case, it would be perhaps better to introduce different names of the parameters - e.g. `resolutionx` (for resolution along the trajectory), `resolutiony` (for resolution along the axis in the horizontal plane perpendicular to the trajectory) and `resolutionz` (for resolution along the vertical dimension). Or, alternatively, just a single `resolution` parameter where the values for individual axes would be comma separated (e.g. `resolution=50,20,10`) or slash separated (e.g. `resolution=50/20/10`). What do you think about it?

**Comment by m-burgoyne** [comment]
@pavol-novotnyI was only suggesting that the `interpolation` parameter could be removed,  the collection business logic would be responsible for generating the best available path for the available data but still allow the user a choice (if appropriate) of how to interpolate the width and height values for the corridor.

 I think the suggestion of dropping interpolation for all parameters would simplify the API even further (providing a more consistent user experience) and renaming the query parameters resolutionx, resolutiony, resolutionz and resolutiont could provide better clarity for consumers of the API.

**Comment by chris-little** [comment]
@m-burgoyne @pavol-novotny I suggest we discuss this in the WG meeting tomorrow, with the presumption that we remove interpolation in this version of the standard. This avoids the difficulties of presenting to the user that some single dimensions can be interpolated readily and obviously, whereas other single dimensions need special techniques, such as logarithmic, to get sensible results, and other interpolations are only sensible in 2, or sometimes more, dimensions. We can then table an extension OGC API EDR: Part n, Interpolation, perhaps optional conformance classes.

**Comment by pavol-novotny** [comment]
@chris-little Do you mean to remove the *interpolation method* just from the `/corridor` data query? Or, to remove it from the other data queries (`/position`, `/area`, `/cube`, `/trajectory`), as well?

**Comment by m-burgoyne** [comment]
@chris-little @pavol-novotny I assumed that it was `/corridor` and `/trajectory`

**Comment by chris-little** [comment]
@pavol-novotny I meant all of them. For meteorological and oceanographic data, interpolation is a specialised expert topic. As a meteorologist, I would be very unhappy with a user retrieving some rainfall (convective shower) data then applying bilinear interpolation. In the initial simple API case, the server software 'chooses' the 'best data', including choosing not to supply any. (e.g. user requests wind speed and direction at -10m.)

**Comment by chris-little** [comment]
@pavol-novotny @m-burgoyne Is this interpolation an 'information only' metadata returned to the user, or can they specify it as part of the data retrieval? I am content with the idea on removing from all the queries, but exposing it as metadata where applicable.

**Comment by m-burgoyne** [comment]
@chris-little the user can specify it as part of the query from the a list of available options described in the metadata.  Removing interpolation as a user choice would make the API much easier to use and simplify interoperability.

**Comment by pavol-novotny** [comment]
So, if I understand your suggestion properly, it implies the following changes in the parameters of data queries:
* `/position`:
  * The query parameters `interpolation` and `interpolationz` will be completely removed.
  * Note: If my suggestion from the issue #45 regarding extension of the `z` parameter was accepted, then a new parameter `resolutionz` would make sense to get a vertical profile at the specified position in 2D.
* `/area`:
  * The query parameters `interpolationx` and `interpolationy` will be replaced by new parameters `resolutionx` and `resolutiony` (or rather a single parameter `resolution`?).
  * The query parameter `interpolationz` will be completely removed. 
* `/cube`
  * The query parameters `interpolationx`, `interpolationy` and `interpolationz` will be replaced by new parameters `resolutionx`, `resolutiony` and `resolutionz` (or rather a single parameter `resolution`?).
* `/trajectory`:
  * The query parameter `interpolation` will be replaced by a new parameter `resolution` (to define the number of samples along the trajectory). Actually, I am not sure in this case if the intended use is to get the data exactly at the points specified in the `coords` parameter, or if rather a sampling along the specified trajectory is expected. Obviously, the `resolution` parameter would be needed just in the latter case.
* `/corridor`:
  * The query parameters `interpolation`, `interpolationwidth` and `interpolationz` will be replaces by new parameters `resolutionx` (`resolutiont`?), `resolutiony` and `resolutionz` (or rather a single parameter `resolution`?).
  * Note that the resolution for the axis running along the trajectory is a little bit tricky for corridors running over a time range. If the speed is not constant for the whole trajectory, then an equidistant sampling in time differs from an equidistant sampling in space. I guess that an equidistant sampling in time makes more sense. On the other hand, for the other types of corridor an equidistant sampling in space is the only option.

@m-burgoyne @chris-little Is my understanding of the suggested changes correct?

**Comment by m-burgoyne** [comment]
@pavol-novotny @chris-little Yes that is a good summary of the proposal

**Comment by pavol-novotny** [comment]
> Actually, I am not sure in this case if the intended use is to get the data exactly at the points specified in the `coords` parameter, or if rather a sampling along the specified trajectory is expected.

@m-burgoyne Please, can you clarify this issue?

**Comment by m-burgoyne** [comment]
@pavol-novotny , for `/trajectory` resolution would define the number of samples along the path, if a resolution value was not defined then it would return the values for the requested locations defined by the specified  `coords` 

That is if it was appropriate, if the values did not match locations in the underlying data and the collection logic did not support interpolation a not found error would be raised

**Comment by m-burgoyne** [comment]
Interpolation parameters have been removed from the API
