### ISSUE TITLE
'/area' query and multi-polygons

### ISSUE THREAD

**Issue by iandruska-ibl** [opengeospatial/Environmental-Data-Retrieval-API#48]
Current specification draft allows requesting multi-polygon from the /area endpoint (https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/requirements/edr/query_type/polygon.adoc). However, it is not clear to me how horizontal sampling should work in this case.

For a single polygon, I would
1. construct a bounding box around the polygon,
2. sample the data into the bounding box according to requested `resolutionx`/`resolutiony` (assuming the new resolution parameters https://github.com/opengeospatial/Environmental-Data-Retrieval-API/issues/47#issuecomment-617891406, but the same applies to the former `interpolation[xy]` parameters)
3. return the intersection of the resulting rectangular grid with the requested polygon.

However, I am not sure how to interpret `resolutionx` and `resolutiony` for a multi-polygon. Does it apply for each polygon separately, or to the union of all polygons?

**Comment by m-burgoyne** [comment]
@iandruska-ibl It would apply to each polygon separately

**Comment by chris-little** [comment]
@m-burgoyne I do not think that I agree. If separate resolutions could be specified for each polygon component, then it would be identical to separate polygon queries. This of course has implementation advantages.
I think that the purpose of a multi-polygon is to cover the case of a clipped polygon (becoming several separate pieces) or small islands in lakes on bigger islands in seas. 
In these cases, the same resolution for component parts of a polygon would give more predictable results for end users. It is what I would expect.

**Comment by iandruska-ibl** [comment]
@m-burgoyne @chris-little Since there is only one `resolution[xy]` parameter, the same resolution would apply to each polygon. In that case, the grid spacing (distance between grid points) would be different in each polygon, as it depends on the size of the polygon. A tiny polygon would have grid spacing of let's say 1 m while a thousand times larger polygon would have resolution of 1 km. The results would be unpredictable and confusing to end users, I am afraid.

**Comment by iandruska-ibl** [comment]
@chris-little
> small islands in lakes on bigger islands in seas

Do you mean polygon with holes? https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#/media/File:SFA_Polygon_with_hole.svg

**Comment by m-burgoyne** [comment]
@chris-little the argument against is that it would complicate the API, the WKT standard gives a well-defined approach to requesting multi-polygons (MULTIPOLYGON) the problem would be on how you  map the required resolutions to the correct polygons.
If there was a requirement for different resolutions for each polygon, I think the best approach is that the user would have to split up the query into multiple requests one for each resolution change.  This would simply the query interface, making implementation and consumption of the API more straightforward.

**Comment by iandruska-ibl** [comment]
@m-burgoyne Are you suggesting to remove the MULTIPOLYGON support from the /area query? If yes, I strongly agree. Not only the interpretation of `resolution[xy]` parameters would be much more straightforward, but also the output handling would be more straightforward (multi-polygons are okay for CoverageJSON, but in case of GRIB each polygon would have to be encoded in a separate GRIB anyway, just as if user issued separate /area query for each polygon).

**Comment by m-burgoyne** [comment]
@iandruska-ibl I was only suggesting that there could only be a single set of resolution values for all of the polygons requested.  I do agree that MULTIPOLYGON will complicate the API and it might be better if any MULTIPOLYGON requirement was handled by processing systems downstream of the EDR API, as this would allow a wider range of formats (and storage/query technologies)   to support the `/area` query pattern

**Comment by iandruska-ibl** [comment]
@m-burgoyne 
> single set of resolution values for all of the polygons requested

This would be very hard to achieve since `resolution[xy]` are expressed as a number of samples. N samples across a small polygon will result to a different actual resolution (distance between grid points) than N samples across a larger polygon. This would only confuse end users, I think.

A solution would be to somehow determine a common frame of reference for all polygons. But I reckon that would be very tricky to implement correctly. Even if implementers manage to do so, the logic might be confusing to the end user, I am afraid.

I believe it would be best to omit multi-polygons. To force users to issue multiple /area queries. For their own good. Do you agree?

**Comment by m-burgoyne** [comment]
@iandruska-ibl Yes I agree  removing  MULTIPOLYGON capability would not reduce functionality, and whilst it will increase the inconvenience of having to make multiple requests to the consumer it would simplify interoperability and implementation for API providers.

**Comment by chris-little** [comment]
@iandruska-ibl @m-burgoyne So how do we support plygons with holes? Or "nested" holes? If the current minimalist approach of 'simple polygons only' suggested above is taken, I propose that we support polygons with hoels as a future enhancement.

**Comment by iandruska-ibl** [comment]
@chris-little Polygons with holes are represented by the POLYGON geometry, so they are still supported. MULTIPOLYGON represents a collection of independent polygons. There are nice examples at https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

**Comment by chris-little** [comment]
@m-burgoyne @iandruska-ibl OK I think we have agreed. First version of EDR API supports Polygon (with or without holes), as defined by WKT.
We defer MultiPolygon to a later version, or enhanced version, or not at all.
