### ISSUE TITLE
Future work: 3/4D corridors

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#50]
see https://github.com/opengeospatial/EDR-API-Sprint/issues/10#issue-580257154

**Comment by chris-little** [comment]
Retrieve data from various data stores throughout a specified 'corridor' (i.e. a 'fat trajectory').

A 4D corridor, through a 3D volume but over a time range
( (x1,y1,z1,t1), (x2,y2,z2,t2), ...(xn,yn,zn,tn) ) plus r,z ranges.
This is the primary goal, driven by various use case, such as an aviation flight path. Other cases below are not so convincing,

A 3D corridor on the surface of the earth but over a time range. ( (x1,y1,t1), (x2,y2,t2), ...(xn,yn,tn) ) plus r range. This maybe needed for the Wuhan University objective., with a use case of a trajectory path and area of influence from a typhoon/hurricane forecast.

A 2D corridor on the surface of earth, at the same time. ( (x1,y1), (x2,y2), ...(xn,yn) ) plus r range. This is just a specialised 2D polygon, with a different specification of the boundary

A 3D trajectory, through a 3D volume with height or depth, for the same time
( (x1,y1,z1), (x2,y2,z2), ...(xn,yn,zn) ) plus r,z ranges. This is just a specialised 3D polygon, with a different specification of the boundary

**Comment by m-burgoyne** [comment]
@chris-little, the `/corridor` definition is intended to handle those use cases
