### ISSUE TITLE
Allow a polygon to be extended in both time and vertically together

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#55]
This was discussed in the Sprint. We agreed that a Position query could be extended in time to a time series (1D), or extended vertically into a vertical profile (1D), but not both at the same time (2D). 
https://github.com/opengeospatial/EDR-API-Sprint/issues/6#issue-580247225 

The same argument applies to an Area query which could be extended in time to a time series (3D), or extended vertically into a vertical prism (3D), but not both at the same time (4D).

The main reason against supporting these now is not really technical, but the size of the returned payload.

I propose both these options as future work.

**Comment by m-burgoyne** [comment]
@chris-little I disagree, I would not add vertical support to the `/position` query and `/cube` already handles the vertical requirements you mention for `/area`.
I believe that the `/position` query can reach the widest audience,  there are already a huge range of custom API’s that perform the give me data for location x,y. So there are already a large number of applications which could utilise the capability as long as we don’t over complicate the API by adding functionality that 95% of users will not want.
I think that `/trajectory` can be used for the vertical profile requirement.

**Comment by pavol-novotny** [comment]
@chris-little @m-burgoyne This is related to my questions in #45. My idea is to extend the meaning of the `z` parameter so that it could be a single value as well as a range (analogically to the `time` parameter). Support of the range might be optional (to be decided by the implementer of the given collection). If such a `z` parameter was added to the `/position` query, it could be used to query a vertical profile conveniently. This would be more intuitive for the users than using the `/trajectory` query where the sampling is very tricky in general as discussed under #53.

**Comment by m-burgoyne** [comment]
@pavol-novotny @chris-little , I am still concerned that this increases the complexity of the `/position` API for a vast majority of use cases were there will be no vertical levels to query.  I am afraid I don't understand why the sampling would be any simpler as it is only a difference in how the  query coordinates are passed to the collection and as far as I can tell all of the issues you have identified  with using `/trajectory` would exist with `/position`.

**Comment by pavol-novotny** [comment]
@m-burgoyne Inclusion of the `z` parameter might be optional. Thus, I believe it would not increase the complexity of the `/position` API for use cases were there will be no vertical levels to query.

The fundamental difference between the `/position` and the `/trajectory` query is the same as mentioned by @iandruska-ibl in https://github.com/opengeospatial/Environmental-Data-Retrieval-API/issues/53#issuecomment-621701698 - the direction of trajectory segments in general is not parallel to the `x`, `y`, `z`, `t` dimensions and so the meaning of the resolution is unclear. On the other hand, my suggestion is to introduce the following optional parameters for the `/position` query:
* `z` - It could be a single value as well as a range.
* `resolutionz` - The number of samples along the `z` dimension (only to be used if `z` is a range). If not specified, the data for all available levels in the specified range would be returned.

If the user specified both `time` and `z` as a range, he/she would get a 2D array of values representing a vertical profile changing in time. I am not sure if this can be achieved by the `/trajectory` query.

**Comment by chris-little** [comment]
Use case for a z in the Position query: 
1. Retrieve wind speed and direction at 50m above the ground, for a crane operator.
2. Retrieve wind speed and direction at every 10m up to 50m above the ground, for a crane operator.
3. Retrieve wind speed and direction on the ground, for a crane operator.

**Comment by chris-little** [comment]
Specifying Z for various queries is a valid option for Position, Radius, Area and Cube now. 
Spcifiying T value or duration is a valid option for variojs queries now.

Both togethere is an enhancement
