### ISSUE TITLE
Reference list for people to come up to speed?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#6]
I've been looking for some reading to get people up to speed on the prior work that led up to EDR. 

The best I've been able to find thus far is here: https://github.com/opengeospatial/Weather-on-the-Web-ER/blob/master/7-challenges.adoc

Are there other resources that people should read to get caught up?

**Comment by chris-little** [comment]
I’ll bring some reference together for later.

**Comment by chris-little** [comment]
@dblodgett-usgs I nowe think this is reasonably comprehensive, from the absolute basics through to WotW experiences.

**Comment by dblodgett-usgs** [comment]
This was closed with: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/BackgroundReading.md
