### ISSUE TITLE
Interpretation of the corridor 'z' axis

### ISSUE THREAD

**Issue by pavol-novotny** [opengeospatial/Environmental-Data-Retrieval-API#61]
![corridor_height](https://user-images.githubusercontent.com/63053940/81548430-951b2280-937d-11ea-8663-ad7b4d4edbc0.png)
I wonder what is the interpretation of the **`z` axis** - and the related **corridor height (H)** - in the `/corridor` request. I can see two different interpretations:
A) The `z` axis of the corridor is parallel to the `z` axis of the original grid, i.e. it is a **vertical line** in the true 3D space. 
B) The `z` axis of the corridor is perpendicular to the given trajectory segment, i.e in general it is **not a vertical line** in the true 3D space.

Which interpretation is the correct one?

**Comment by m-burgoyne** [comment]
@pavol-novotny In order to make it easier to explain to users I think it would make sense for the z-axis to always represent the vertical line in the true 3D space.

**Comment by pavol-novotny** [comment]
@m-burgoyne Is there an assumption that the slope of the segments will never be too steep? Otherwise, the results might be quite counterintuitive.
![corridor_height_steep](https://user-images.githubusercontent.com/63053940/81564010-5f833300-9397-11ea-9b15-8eb040d24f5d.png)

**Comment by m-burgoyne** [comment]
@pavol-novotny I think that problem is easier for users to understand than trying to explain that the z-axis direction is dependent on the data response.

**Comment by chris-little** [comment]
@m-burgoyne @pavol-novotny If we discourge the use of Trajectory for vertical profiles, we are assuming that trajectories are mainly quasi-horizontal, and therefore realistic assuming the gradients of a Trajectory are not too great. I think that this would the general assumption by users.

**Comment by pavol-novotny** [comment]
@chris-little So, the expected use cases are limited to typical trajectories of airplanes. Use cases like a rocket trajectory are out of scope. Correct?

**Comment by chris-little** [comment]
@pavol-novotny Good point! I propose that we make the first version of EDR API, all query patterns, only return the data that is available for the points requested.
Any form of interpolation or resolution request should be enhancements for later versions.

**Comment by chris-little** [comment]
@pavol-novotny @m-burgoyne Though we still need to agree on the 'depth' of a corridor. 

'Depth' orthogonal to the direction of the corridor is the most natural, as this reflects what happens in the horizontal x-y plane - we do not choose a projected width but assume the width is orthogonal to the direction and then the x, y component distances can be calculated.

**Comment by chris-little** [comment]
Consensus in the EDR API SWG #11, that the x,y,z directions for width and depth of corridor should be orthognal to the direction of the corridor at that point.
Only remaining issue is how the 'depth' is calculated when the vertical data coordinate is pressure rather than altitude. Horizontal grids are generally evenly spaced in both x and y, but this is not true for pressure levels in the vertical. They are close to a logarithmic spacing. 
So, saying the width is 5 km on either side of the trajectory centre line of a corridor gives a symmetrical buffer. Saying the depth is 50hPa above and below the centre line is not symmetrical, it is deeper (in altitude) above the line than below it.
Is this acceptable or not?

**Comment by pavol-novotny** [comment]
@chris-little I mean that the logarithmic spacing is not the only issue. I think that the **orthogonal** direction is **not well defined** for a space where the `x` and `y` dimensions of the source grid are in metres and the `z` dimension is in hPa. For illustration - imagine an extreme case, a trajectory containing a vertical segment - if you say that the height (depth) is 50hPa, what do you actually mean (see the picture)?
![corridor_height_vertical](https://user-images.githubusercontent.com/63053940/82036572-5947cc00-96a1-11ea-8cdf-59d3f442d406.png)
Note that for a corridor containing vertical segments, there is an additional issue: in that case even the `y` axis along that the width is defined (laying in the horizontal plane and perpendicular to the trajectory segment) is not well defined - any direction in the horizontal plane can be chosen (i.e. the box around the vertical trajectory segment can be rotated arbitrarily). However, this issue does not depend on the interpretation of the `z` axis of the corridor and is not limited to a case when the `z` dimension is in hPa - it is a general issue of the corridor's definition.

**Comment by chris-little** [comment]
@pavol-novotny OK. We agree that for the same UoM in 2 or more dimensions (let us say km), there is no problem. we just project onto the axes, or use Pythagoras' Theorem.
For mixed coordinates, let us say just two, x and P, choosing the orthogonal direction to the trajectory is problematic. As you say, a vertical trajectory would have a corridor width measured in purely X, and a horizontal trajectory would have a width measured purely in hPa. A sloping trajectory would have a width measured depending on dP/dX (or do I mean -dX/dP?) 

So why can we not choose a corridor width in hybrid units d such that d**2= dp**2 + dX**2? If the trajectory has a small gradient, the width is mainly hPA. If the trajectory is steep, the width is mainly km?

If people are unhappy with this approach, we can just adopt a fixed relationship between pressure and height - the ICAO standard atmosphere. But the complicaation with this apporach is that the depth of the corridor will explicitly vary significantly with height.

**Comment by pavol-novotny** [comment]
@chris-little I think that hybrid units combining metres with `hPa` would be very confusing for the users. If there is a consensus that the `z` axis should be perpendicular to the given trajectory segment, then I believe that height and width should be specified in consistent units (metres or kilometres) even if the native `z` dimension of the given collection is in `hPa`. It should be let up to the implementer to decide how the internal conversion from `hPa` to metres will work - using ISA or using the geopotential height field if available. Or, the implementer might decide not to support the `/corridor` data query for such types of collections.

Alternatively, we might reconsider the meaning of the `z` axis. If it was always a vertical line in the true 3D space regardless of the slope of the given trajectory segment, then the height could be specified also in `hPa`. On the other hand, this would reduce the usability of this data query to use cases, when the trajectory slope is not too steep. Perhaps, it would be sufficient for an airplane use case, but not suitable for a rocket use case.

The third option would be to allow both ways of the `z` axis interpretation. Perhaps, there might by an additional parameter (e.g. `zaxisdirection`) with two possible values:
1. `vertical`
2. `perpendicular` (or `orthogonal`)

The implementer might decide which option would be supported by the given collection (just one of them, or both).

**Comment by chris-little** [comment]
@pavol-novotny I do not envisage that the end user would be exposed to hybrid units. They could choose one depth and UoM. If the UoM is hPa, this implies the first section of the corridor, perhaps of zero length, would be horizontal. If they choose UoM as km, this implies that the first sectin of the corridor is vertical. In either case, the hybrid width/depth of the next section is calculated, using either a fixed ICAO atmosphere or the actual data, on the server side and the data returned. 

Allowing both vertical and orthogonal depths as options seems sensible. The users will need to warned that 'vertical' is not good for vertical corridors!

**Comment by chris-little** [comment]
Discussed at length in EDR API Meeting 14 telco. 

We agreed that the first version of the EDR API would specify the corridor depth along the vertical coordinate axis in Units of Measure of that axis. E.g. hPa or metres. This is Diagram A. The horizontal width of the corridor would be orthogonal to the trajectory axis. This approach meets the widespread use case for aviation, as aeroplanes generally fly relatively level, unlike a rocket or artillery shell (see Diagram C).

The case of Diagram B, where the depth of the corridor is not perfectly vertical, but orthogonal to the trajectory, is more appropriate for steeply inclined corridors, such as for a rocket. This is an enhancement for a future version.

**Comment by chris-little** [comment]
The case of specifying the corridor size by a single radius value around the trajectory is also postponed for a future EDR API version. It does not fit the aviation use case where the corridors are typically wide and shallow.

Both future enhancements will have to tackle the problem of mixed Units of Measure for the different coordinate directions
