### ISSUE TITLE
Parametrisation of the output format

### ISSUE THREAD

**Issue by pavol-novotny** [opengeospatial/Environmental-Data-Retrieval-API#67]
I wonder if the output format can be parametrised. E.g. if you want to use the `/cube` data query and return the data as a JPEG image with a specified quality:
1. Can the EDR implementer introduce a custom `quality` parameter to allow requests like this: `.../cube?...&outputformat=JPEG&quality=50`?
2. Perhaps, an alternative way might be to include the custom parameter as a part of the value of the `outputformat` parameter like this: `JPEG;quality=50`. However, the specification says:
> The `outputformat` parameter SHALL consist of an string value based on an enumerated list of available options provided in the collections metadata.

I am not sure if this would mean that the string `JPEG;quality=50` had to be explicitly enumerated in the list of available options together with other options like: `JPEG;quality=100`, `JPEG;quality=99`, `JPEG;quality=98`, ..., `JPEG;quality=1`. Or, could there be something like this in the metadata instead: `JPEG;quality=*`?

**Comment by chris-little** [comment]
@pavol-novotny This is very like the 'resolution' and 'interpolation' issues. It would be consistent if we said the first version of the standard returns whatever the underlying quality is. 

I think the intent of "explicitly enumerated in the list of available options" would be strings like: JPEG, JSON, BUFR, CSV, XML, etc

**Comment by chris-little** [comment]
as agreed in EDR API #13 telco. Ehancements to be closed
