### ISSUE TITLE
Link relations in EDR?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#72]
If we introduce additional end points under `/collections/{collectionID}/` we need to figure out what link relations to use for them. `items` is used in Features and I am not aware of any precident for what to use.

My initial suggestion is to just use the path literal, but there may be an argument for using a resolvable URI that would describe the nature of the link.

**Comment by dblodgett-usgs** [comment]
See: https://github.com/opengeospatial/oapi_common/issues/76 and https://github.com/opengeospatial/ogcapi-features/issues/383#issuecomment-638775455 

The OGC-NA will be deciding how to or if we should handle link relations defined in an OGC URI space. This would lead to link relations like: `http://www.opengis.net/def/rel/ogc/1.0/area`

**Comment by chris-little** [comment]
@dblodgett-usgs Currently, I think that the draft EDR API only uses link relations that are in OGC API - Features, OGC API - Common and the IANA registry, so we are good to close this issue?

**Comment by dblodgett-usgs** [comment]
What about link relations to the EDR query end points?

**Comment by dblodgett-usgs** [comment]
In https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/2020-06-25 we discussed this and decided that we are open to registering three additional link relations for the query patterns but want to remain open to what API Common and The OAB think.

**Comment by chris-little** [comment]
To clarify: the link relations would be:
Position
Area
Trajectory
?

**Comment by chris-little** [comment]
Note added to link section of draft
