### ISSUE TITLE
Number of conformance classes

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#77]
When editing the June Draft, I increased the number of conformance classes. This was a mistake, I think, as I was mixing up conformance classes and requirements classes.
Conformance class: related to how a product is certified: "This product is certified to do ..."

There may be several Requirements Classes in each Conformance Class: "This product is certified to do ... by meeting requirements a, b, c, ..."

I propose that: there should be:
 one Conformance Class for all query patterns.
 one Requirement Class for each of the patterns: Position, Area, Trajectory.

**Comment by cportele** [comment]
@chris-little - This won't work. There is a 1-to-1 relationship between requirements classes and conformance classes as specified in the [OGC specification model (mod spec)](https://portal.opengeospatial.org/files/?artifact_id=34762). 

By the way, conformance in the specs isn't about products, but depends on the specification target and in the EDR case will be individual APIs. Products only come into play with CITE and certification.

**Comment by chris-little** [comment]
Need to clarify the three types of confomrance class:
1. idnetical to other API
2. extends other API
3. unin
que to this API

**Comment by chris-little** [comment]
How about having the /instance/{instanceId} component as a separate conformance/requirements class? This would perhaps make it easier to make part of API - Common. It could be useful elsewhere besides API-EDR.
