### ISSUE TITLE
Cross-sections as cubes?

### ISSUE THREAD

**Issue by tervo** [opengeospatial/Environmental-Data-Retrieval-API#78]
Questions: are cross-sections thought to be flat cubes or are they out of scope? They _could_ be queried as cubes like: 
`&coord=POLYGON(-6.0 50.0,-4.35 50.0,-4.35 50.0,-6.0 50.0,-6.0 50.0)&minz=0&maxz=300&resolutionx=10&resolutiony=10&resolutionz=10`

**Comment by m-burgoyne** [comment]
@chris-little my view on this (as with most other similar questions) is that it is a collection provider decision, as long as the WKT string is valid and the query parameters are correctly specified for the API endpoint, queries can be supported.  When a provider does not support degenerate queries an error message should be returned which provides an explanation of which query parameters were invalid and ideally provide suggestions as to how the user could remedy the issue.

**Comment by tervo** [comment]
Sounds good solution to me. 

It is notable that for example self-cutting polygon support is typically very hard to implement with good performance and many providers may want to drop the support.

**Comment by chris-little** [comment]
@tervo To summarise:
1. We are not excluding a vertical cross-section retrieved via the Area query using a slightly degenerate polygon. 
2. Retrieving a vertical cross-section by using a Cube query is exactly same as Cube is defined using WKT Polygon.
3. It could be an extension of the Trajectory (what we defined as a 'curtain' in the Met Ocean extensions to WCS/CIS). It would make sense to include this in future work, along with Corridor delinted by the surface, or a surface. Having such a curtain/trajectory with two horizontal positions could give a precisely defined vertical planar cross-section.

**Comment by chris-little** [comment]
Agreed to close.
Useful principle indicated of response data dimension is same as query geometry dimension.
