### ISSUE TITLE
2 or 3 requirements classes for JSON, geoJSON and covJSON

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#79]
The test that we have imported from OGC API - Common groups JSON and geoJSON together for some conformance testing. I think it is clearer if these are separated, so that there are three separate conformance/requirements classes. JSON is requirement for some (non-spatial) metadata, geoJSON for simple spatial info such as bounding boxes, and CoverageJSON as the highly recommended format for EDR.

**Comment by dblodgett-usgs** [comment]
Are they all three just particular JSON-schema? I think I prefer to treat JSON-schema the same regardless of what schema they conform to.

**Comment by chris-little** [comment]
@dblodgett-usgs Both GeoJSON and CoverageJSON are JSON, but restricted. CoverageJSON is not a restriction of GeoJSON.
Just checking for JSON validity may be good enough for some things, but not if we want automatic consumption of CoverageJSON. Currently I do not think that there is a validation test suite for CoverageJSON other than the various implementation that consume it.
