### ISSUE TITLE
Ability to specify multiple levels

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/Environmental-Data-Retrieval-API#83]
When the height coordinates were specified by the WKT string in the `/Position` and `/Area` queries it was possible to request multiple vertical levels with a MultiPoint and MultiPolygon WKT definition.  

We could reinstate this capability by allowing the Z query parameter to support a range

**Z=min value / max value**, which would return values all levels between the min value and the max value

i.e. `Z=10/100`

and list of levels **Z=val1,val2,val3** which would return values at the specified levels

i.e. `Z=2,10,80`

**Comment by solson-nws** [comment]
Could a Z direction (up vs down) be incorporated to allow a user the
ability to control the direction?

Steve

**Comment by m-burgoyne** [comment]
@solson-nws I think that is more a data response ordering issue and I would leave that up to the collection provider rather than adding another query parameter to the API

**Comment by ShaneMill1** [comment]
Hey Mark- If the provider wanted to add that query parameter, they could right? As a provider, you just have to meet the core requirements and they could extend if they needed to? Or am I misunderstanding that.

**Comment by m-burgoyne** [comment]
@ShaneMill1 Yes, but it wouldn't be part of the EDR specification so the data ordering so would be ignored by other EDR API's.

**Comment by pavol-novotny** [comment]
@m-burgoyne I agree with your proposal. Actually, it is very close to what I suggested in issue #45, i.e. to treat the `z` and `time` dimensions in a similar way. If we allow to specify a **list of levels**, perhaps we might allow to specify a **list of times**, as well, like this:
`time=2020-06-18T00:00:00Z,2020-06-18T06:00:00Z,2020-06-18T15:00:00Z`.
What do you think about it?

**Comment by m-burgoyne** [comment]
@pavol-novotny I think it would be a good idea, although it is not part of the ISO8601 specification it would provide a consistent approach to defining the dimension coordinates to the queries.

**Comment by chris-little** [comment]
Each element of the list adheres to IETF RFC 3339, and it makes no statement about comma separated lists.
And it is not a WKT component.
So no objections

**Comment by dblodgett-usgs** [comment]
Fixed in #85
