### ISSUE TITLE
Asynchronous requests.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#89]
We discussed this a bit on the [EDR call on July 2nd.](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/2020-07-02)

The current draft spec describes an asynchronous query model using [HTTP Code 308 and end-point redirection.](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/34b69565fed32e3e68a0c278614a5b6533abb37c/candidate-standard/clause_9_general.adoc#asynchronous-queries)

The Processes API spec uses a more resource-oriented [processing "job" model.](https://htmlpreview.github.io/?https://github.com/opengeospatial/wps-rest-binding/blob/master/docs/18-062.html#truerequest-body)

I don't think we want to treat EDR queries as processing jobs, but we do need to pay a bit of attention to asynchronous requests. Has this been tested? Are there any examples we can point to of this pattern being implemented in the wild?

**Comment by chris-little** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308  gives browser support - every thing except Edge <v12 .
Do not be put off by the "Permanent" redirect label - according to Mark, it is to a new object, so permanent for life of the resource.

**Comment by dblodgett-usgs** [comment]
The trick is that Retry-After isn't as well supported. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

**Comment by m-burgoyne** [comment]
Part of the assumption of this approach was that any query that was asynchronous would probably not be made via a web browser.  By using existing web standards, the idea was to provide a solution which would not impose too many technical constraints on the API provider and still be straightforward for client developers to consume in any modern programming language.

**Comment by chris-little** [comment]
We agreed at EDR API SWG 19 that asynchronous response was a Best Practice and should be captured there. Leave some informative text in the spec highlighting different apporaches that could be taken.
When text written, we can close issue.

**Comment by chris-little** [comment]
agreed at EDR API SWG21
