### ISSUE TITLE
Security Aspects of EDR API

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#9]
We need to think about security aspects of the APIs and services built upon them.

One easy approach is to say that all aspects of security are addressed by the supported features of OpenAPI V3, and security is largely orthogonal to the API.

However, if one is requesting environmental data over open links, it may be a security risk. E.g. lots of requests for data, of whatever pattern, connected with a specific region or location, such as:
   lat=55.033564, lon=-2.778538 

This could be mitigated by ensuring the query, and the data returned, is over secure links. Then the security of the server side needs to be addressed, such as its logs, and the client for that matter.

I suspect we can get away with a statement about not exposing the query and the results.

**Comment by m-burgoyne** [comment]
I think the load management and Authentication and Authorization aspects of the API query are outside of the scope of the EDR and are better handled by off the shelf technologies such as API Management software [https://en.wikipedia.org/wiki/API_management](API Management definition).  But we do need to consider how License and Access rights information are provided in the metadata responses of the API.

**Comment by chris-little** [comment]
I agree that load management and Authentication and Authorization aspects of the API query are outside of the scope of the EDR and are better handled by off the shelf technologies such as API Management software API Management definition. I propose that we have such a statement in the "2. Scope" section.

A separate issue to be raised for  License and Access rights via the API

**Comment by cmheazel** [comment]
@chris-little I disagree. 
We ignored security when we developed our web service standards. The result was that compliant implementations could not be secured and secure implementations could not be compliant. Not a good spot to be in.
OpenAPI already allows us to describe some common Authentication and Authorization controls. EDR should identify what additional controls may be needed and make sure the standard does not preclude them. 
The actual specification of the security controls may take place somewhere else, but this is where the requirements come from.

**Comment by chris-little** [comment]
@cmheazel So, in Section 2. Scope, I propose that we add something like: 
"Authentication and Authorization aspects of the EDR API query and response are outside of the scope of the EDR and are better handled by off-the-shelf technologies such as API Management software."

and also add somewhere (2. Scope is probably OK):

"There may be additional security requirements to protect the contents of an EDR API query and its response, and to protect the monitoring and logging of such queries and responses. These are out of scoope of the ERD API standard."  

Is that good enough?

**Comment by cmheazel** [comment]
@chris-little What we are moving toward is a security considerations section. Provide a short discussion on how implementations of this standard would work with off-the-shelf technologies and which ones we see as relevant to the identified use cases.

**Comment by chris-little** [comment]
Agreed EDR APi SWG #11

**Comment by dblodgett-usgs** [comment]
@chris-little I thought we agreed that these enhancement issues would remain open but be addressed in a future part of the spec?

**Comment by chris-little** [comment]
@dblodgett-usgs I think I need to revise how Milestones work!
