### ISSUE TITLE
Test text: parameters in text be quoted with back-ticks

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#91]
Should parameters, like `resolutionx` be enclosed in back-ticks/grave accents throughout the document?

**Comment by chris-little** [comment]
As parameters etc are snippets of code, it is good GitHub practice to enclose in backticks (grave accents, to left of '1' on English MS Windows Keyboard. It also avoids invoking GitHub 'magic' behaviour when special characters like `#` and `@` are used. I have already annoyed someone called KR who cannot speak Korean when using language tags `@kr`.

**Comment by dr-shorthair** [comment]
Mind you, if you grab a standard language tag as your moniker, then you probably should expect (and tolerate) some consequences. I deleted his/her rant from the github issue thread because its length overwhelmed the actual issue topic.

**Comment by chris-little** [comment]
@dr-shorthair You are lucky that the Dominican Republic went for `@do` !

**Comment by chris-little** [comment]
As agreed at the EDR API SWG on 2020-07-09, Pull Request now being constructed with reordered chapters and all instances of `code` delimited by back ticks.
