### ISSUE TITLE
Add cross-linked glossary appendix.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#95]
As part of a discussion about important but non-normative terms in OGC specs, I volunteered to implement a glossary of terms for EDR.

In the next few weeks, I'll work through the document, collecting such terms from documents and work this up in a branch for the group to consider. 

I'll take inspiration from the W3C spatial data on the web best practice: https://www.w3.org/TR/dwbp/#glossary

**Comment by chris-little** [comment]
@dblodgett-usgs I'll put place holders for Position/Area/Trajectory/etc in my PR. I have not found any definitions that we can use, other than ISO calling a trajectory a path with a time parameter.

**Comment by ghobona** [comment]
**position**:  data type that describes a point or geometry potentially occupied by an object or person (ISO 19133:2005)

See https://www.iso.org/obp/ui/fr/#iso:std:iso:19133:ed-1:v1:en

**trajectory**: path of a moving point described by a one parameter set of points (ISO 19141:2008)

See https://www.sis.se/api/document/preview/909843/

**Comment by dblodgett-usgs** [comment]
@chris-little by my understanding, those should be in our normative definitions. 

The Glossary is a place to put definitions from other standards that are critical to understanding this standard. In particular, terms from the Mod Spec. I did not plan on actually inventing or debating definitions as part of this issue.

Are there other terms we should pull in that are maybe normative in a related standard?

**Comment by dblodgett-usgs** [comment]
TODO:

 - [ ] add additional definitions
- [ ]  vet definitions with the SWG
- [ ]  add references / bibliography entries
- [ ]  cross-link glossary and references into text in appropriate places

**Comment by chris-little** [comment]
2020-10-15 agreed to close
