### ISSUE TITLE
Associating `.../items/{id}` to `.../{query}` 

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#98]
We've agreed in the past that the `.../items/{id}` endpoint would be a way to provide discoverability for cached or otherwise already-available environmental data retrieval resources using the API Features / GeoJSON with an [EDR JSON Schema](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/openapi/EDR_OpenAPI.yaml#L2441) that specifies GeoJSON GeoJSON parameters. 

I started a monitoring network mockup here: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/Monitoring-network-mockup and have run into a rather basic question.

If, in the case that we have a monitoring location that is discovered at:  
`https://.../items/123`  
and is also available at:  
`https://.../locations/123` 

How do we cross link the two end points? In the mockup linked above, I've surmised we could do it two ways -- by using a shared id, e.g. `123`, and by using an `alternate` link relation that links to the `locations/123` endpoint or `items/123` endpoint depending which we are talking about with an appropriate media type declaration.

Is this what was intended or is there some other pattern/convention that we've been imagining?

For other queries, where there is no {id} but just a cached query, how do we want to handle this?

**Comment by m-burgoyne** [comment]
An `items/{id}` id value is the identifier for an individual item (and the publisher of the collection will define what an item is).  A `locations/{id}`id value is an identifier for a location (and the publisher of the collection will provide a geospatial definition of the location).

This means that it is unlikely that there would be a mapping of a *locations id* value to an *items id* value but it would be valid for one of the data properties included in the data returned by an `items/{id}` query to be a location defined by `locations/{id}`.  Similarly, the data returned by the locations query could include item id’s for each of the individual items returned.

This would also allow a user to easily identify a collection of items from the same location as they would share the same location id.

The approach allows multiple location views on the same items, for instance the same Metar observation from Paris Charles de Gaulle Airport could be included in location queries where the location is based on areas such as Charles de Gaulle Airport, France, Europe and Global.

**Comment by dblodgett-usgs** [comment]
OK, I think we are heading in the same direction. We need to nail this stuff down though and clarify some things in the spec.

I've updated the [example here.](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/Monitoring-network-mockup)

Importantly, the [`uri` parameter here](https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/openapi/EDR_OpenAPI.yaml#L2469) in the `items` schema is intended to be the EDR API Query Base URI. 

e.g. `"https://.../collections/{cid}/locations/{lid}"` which would then be sub settable according to the datetime and parametername fields included with the `item`. 

The main thing I want to get to is that the items JSON-Schema establishes items as EDR Items that document available EDR Queries. How should we reflect this in the specification?

We have very little in items and locations now... http://docs.opengeospatial.org/DRAFTS/19-086.html#_items_query

There's also a conformance class for features -- maybe it goes there? http://docs.opengeospatial.org/DRAFTS/19-086.html#_features_rootcollectionscollectioniditems

**Comment by m-burgoyne** [comment]
The example looks good to me and I agree the queries need better text descriptions

**Comment by dblodgett-usgs** [comment]
OK -- let me see if I can work up some content in the relevant section of the spec.

**Comment by chris-little** [comment]
agreed to close at EDR API SWG 22
